### ISSUE TITLE
Write the HTML/JS Quickstarts and Documentation

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#10]
Need a set of documents for HTML/Browser and Cordova clients.

**Comment by shrishrirang** [comment]
@adrianhall  Let's use this to track documentation work. If we need quickstart for HTML/JS (in addition to Cordova), can you create a separate issue for it?

**Comment by adrianhall** [comment]
The Cordova quickstarts are already written.  The documentation tasks (as given to the docs teams) are tracked in Trello, since the docs teams do not use github issues.  Those tasks already exist.
