### ISSUE TITLE
What is the "platform" reference for in Client JS file?

### ISSUE THREAD

**Issue by georgeedwards** [Azure/azure-mobile-apps-js-client#105]
I am working through this SDK to support my issue raised [here](https://github.com/Azure/azure-mobile-apps/issues/27), but I am not sure why this import path exists?
[https://github.com/Azure/azure-mobile-apps-js-client/blob/master/sdk/src/MobileServiceClient.js#L8](https://github.com/Azure/azure-mobile-apps-js-client/blob/master/sdk/src/MobileServiceClient.js#L8) it doesn't seem to point to anywhere, `'Platforms/Platform'` doesn't seem to point anywhere, it seems like it should be somethign like this `./Platforms/winjs/Platform`. 

Is that correct or am I missing something?

**Comment by shrishrirang** [comment]
`Platforms` is a browserify alias for conditionally choosing the target (browser, cordova, etc). The reason for using alias was to work around browserify's limitation with conditional require. `Platforms` is defined in Gruntfile.js at the root. Running `npm run build` will resolve the path by referring to the appropriate platforms directory and generate the bundle in the `~/dist` directory.
