### ISSUE TITLE
Calling /.auth/me after logging in returns 401 Unauthorized

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-js-client#106]
Using the example code from here to get user information, it fails with a 401. I can use the client.getTable and .read() off that table successfully.

https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-html-how-to-use-client-library/

```
**How to: Obtain information about the authenticated user:**

The authentication information for the current user can be retrieved from the /.auth/me endpoint using any AJAX method. For example, to use the fetch API:

var url = client.applicationUrl + '/.auth/me';
fetch(url)
    .then(function (data) {
        return data.json()
    }).then(function (user) {
        // The user object contains the claims for the authenticated user
    });

You could also use jQuery or another AJAX API to fetch the information. Data will be received as a JSON object.
```

**Comment by adrianhall** [comment]
You need to add an X-ZUMO-AUTH header that has the contents of client.currentUser.mobileServicesAuthenticationToken - this is a problem in the documentation and I will correct.

**Comment by adrianhall** [comment]
Fixed in docs - will be published on normal schedule.
