### ISSUE TITLE
Unable to call mobileappcontroller url directly using fetch. Returns 401 Unauthorized after logging in.

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-apps-js-client#107]
I'm attempting to use Aurelia for my front end and would like to use fetch calls in certain scenarios. Whenever I call a mobileappcontroller endpoint (tables/apiname) directly after logging in using the example code here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-html-how-to-use-client-library/, the fetch api receives a 401 Unauthorized response. I also get the same response when using fetch in a simple javascript file.

```
import {autoinject} from 'aurelia-framework';
import {HttpClient, json} from 'aurelia-fetch-client';
import 'isomorphic-fetch';

@autoinject
export class Users {
    heading = 'People';
    users = [];

    constructor(private http: HttpClient) {
        http.configure(config => {
            config
                .useStandardConfiguration()
                .withBaseUrl('https://{app}.azurewebsites.net/tables/')
                .withInterceptor({
                    request(request) {
                        console.log(`Requesting ${request.method} ${request.url}`);
                        return request; // you can return a modified Request, or you can short-circuit the request by returning a Response
                    },
                    response(response) {
                        console.log(`Received ${response.status} ${response.url}`);
                        return response; // you can return a modified Response
                    }
                });
        });
    }

    activate() {
        return this.http.fetch('person')
            .then(response => response.json())
            .then(users => this.users = users)
            .then(data => { console.log(data); })
            .catch(error => { console.log(error.status); });
    }

    postSomeJson(user) {
        this.http.fetch('person', {
            method: 'post',
            body: json(user)
        })
    }
}
```

Is it possible to call the apis directly or can support be added?

Thanks,

John

**Comment by adrianhall** [comment]
I suspect the error is 400 Bad Request with content that basically says "You need a ZUMO-API-VERSION header" - per this doc: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-client-and-server-versioning/  - this header is required.  I don't see any code that adds this header in your code.

Is there a particular reason you are not using the Azure SDK for doing the queries?

**Comment by renzska** [comment]
I currently have the zumo api version check disabled, hence the 401. I'm guessing it's the zumo auth header you mentioned in the other issue. Thanks.
