### ISSUE TITLE
Where is the offline data sync?

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-mobile-apps-js-client#114]
I can't find the offline data sync feature in the code or docs.

I do hope it is available for JS clients.

**Comment by adrianhall** [comment]
Hi @SteveALee - replied in email as well - follow issue #14 which is the meta-issue for offline sync.  You can also do a search in issues for [Offline Sync] - these are the individual tasks that make up that meta-issue.  We are currently working on it!
