### ISSUE TITLE
 Allow specifying the $expand attribute on the client

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-js-client#118]
See related issue https://github.com/Azure/azure-mobile-apps-net-client/issues/141

**Comment by aline-almeida** [comment]
Any news on this ?

**Comment by elamalani** [comment]
@aline-almeida Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us in the future. 

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
