### ISSUE TITLE
Make logout async

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#12]
Logout needs to be an async function.

**Comment by shrishrirang** [comment]
Given that login does not request for EA cookies anymore, do we need #12? Does sending just the X-ZUMO-AUTH token to EA's /.auth/logout do anything?

**Comment by phvannor** [comment]
Yes, logout will terminate the session, so both cookies and token will no longer be valid, forcing the user to get a 401 and have to follow a login process next time.

**Comment by shrishrirang** [comment]
For /.auth/logout to work does sending just the X-ZUMO-AUTH token suffice? Or does it need the EA cookie to identify which session (cookie+token) it needs to invalidate?

**Comment by phvannor** [comment]
Both identify the same session, so either would work.  In our case, yes the token would suffice.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/commit/d569b8489406a060c034cddb56088e12cfc179d8 closes this issue by making logout async. Note that logout does not invalidate the token yet and that issue is tracked separately by https://github.com/Azure/azure-mobile-apps-js-client/issues/13
