### ISSUE TITLE
logout() is not working

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-mobile-apps-js-client#146]
It seems as though the logout() function is not cleaning up cookies or other cached data that might have been stored in the InAppBrowser. Therefore when I call logout() followed by login(), I am immediately logged back in with the account that has previously logged in. Instead I was expecting a login screen to appear to allow me to enter different credentials. 

I know I might be able to work around this by clearing the inAppBrowser cache myself, but imho logout() should log out the user completely, taking into account cache / cookies.

**Comment by lukejaylarsen** [comment]
Same issue here :(

**Comment by rob3c** [comment]
FYI For better or worse, Google is deprecating the InAppBrowser login approach in favor of using the system browser and device-wide user login, so any InAppBrowser-specific solution isn't likely to be worth addressing at this point. See https://github.com/Azure/azure-mobile-apps-js-client/issues/194 for details.

**Comment by adrianhall** [comment]
This is a common problem with InAppBrowser.  If you need to do logout(), use the client-flow authentication and the mechanisms for that.
