### ISSUE TITLE
Require non minimized version of the JS client SDK when using ES6 imports

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-mobile-apps-js-client#158]
When I import the client as a ES6 module. eg

  ```import azureMobApp from 'azure-mobile-apps-client';```

I find I have the minimized version of the code. This is highly undesirable when debugging. 

Can it be changed? 

I would expect anyones release builds will minimise and tree shake etc.

**Comment by SteveALee** [comment]
I don't think it's any use but here's [an example of code](https://github.com/OpenDirective/spikes/blob/master/azure-apps/src/testSDKAccess.js) that exhibits this when you debug

**Comment by SteveALee** [comment]
Related to #130

**Comment by shrishrirang** [comment]
The plan is to fix #130 and then point package.json's `main` to the entry module `sdk/src/index.js`. This should address your need as well.

Bundled SDK for those wanting to include it from HTML will still be made available in some manner.

I am leaving this issue open till this is fixed.

**Comment by SteveALee** [comment]
That sounds perfect!

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/pull/197 closes this.
