### ISSUE TITLE
invokeApi() should return a JSON object, not an XMLHttpRequest

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#160]
When we invokeApi(), we return an XMLHttpRequest.

We should return the object resulting from the parsed JSON on success.

**Comment by danderson00** [comment]
We can't return the results from the call - it's async, or maybe I am missing the point? Do you mean this should return a promise?

**Comment by adrianhall** [comment]
It already returns a promise.  The promise should resolve to a JSON object instead of an XMLHttpRequest.

**Comment by danderson00** [comment]
Ahh. Indeed it should.

**Comment by danderson00** [comment]
@shrishrirang As this is a significant breaking change, we must do this ASAP, before GA.

**Comment by shrishrirang** [comment]
Leaving the API unchanged as there is value in returning the XMLHttpRequest object as it can have other valuable information like headers, etc.
