### ISSUE TITLE
Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by iangithub** [Azure/azure-mobile-apps-js-client#161]
I'm creating a cordova project and use azure mobile app + notification hub service. In the cordova project, I add "cordova-plugin-ms-azure-mobile-apps" and "phonegap-plugin-push" plugins, but when run project I get an 404 error

> Failed to load resource: the server responded with a status of 404 - Cannot GET /push/installations/xxxxx(it's a guid string)

step:

 1.use visual studio 2015 create cordova 6.1.1 project 
 2.add phonegap-plugin-push : version="1.7.2"
 3.add cordova-plugin-ms-azure-mobile-apps : version="2.0.0-beta5"

Does the azure notification hub api uri change?
Because I see the "MobileServices.Cordova.js" file , that has " executeRequest " function and call 'push/installations/'.... uri

**Comment by edwardkuo** [comment]
I have the same problem . Url is error or not?

**Comment by adrianhall** [comment]
Let's get the obvious things out of the way first - have you configured a Notification Hub, and have you linked the Notification Hub to your app service?

**Comment by edwardkuo** [comment]
Yes, I have to linked the Notification Hub. If I try to use object-c connection Notification Hub, it is worked.

**Comment by iangithub** [comment]
Yes , I configured Notification Hub and linked to mobile apps .

**Comment by Andvood** [comment]
Having same issue, any solution found?

**Comment by adrianhall** [comment]
Can you share some code?  Particularly the code used to initialize the MobileServiceClient and the code used to do the registration?  You don't need to give the exact URLs, but we do need to see domains.

**Comment by iangithub** [comment]
`var azureClient = new WindowsAzure.MobileServiceClient('https://yourmobileapp.azurewebsites.net');

var push = PushNotification.init({
        android: {
            senderID: "Google Project ID"
        },
        ios: {
            alert: "true",
            badge: "true",
            sound: "true"
        },
        windows: {
        }
    });

push.on('registration', function (data) {
        azureClient.push.register('gcm', data.registrationId);  //404 error
    });
`

**Comment by iangithub** [comment]
I use another solution , create a .net mobile app backend with azure notification hubs sdk and cordova app call our mobile app backend api to register azure notification hubs and use phonegap-plugin-push receive notification message

**Comment by adrianhall** [comment]
Based on this, it sounds like the NH is not linked properly in your Node backend.  I'm glad you resolved it (and so will close this).
