### ISSUE TITLE
Sync from local store to server fails.

### ISSUE THREAD

**Issue by markau** [Azure/azure-mobile-apps-js-client#163]
I am following a combination of the instructions [at the MSDN blog here](https://blogs.msdn.microsoft.com/appserviceteam/2016/06/29/offline-sync-with-azure-mobile-apps-and-apache-cordova/) and in the repo Readme.  The key difference between the two pieces of doco is the instantiation of the `MobileServiceSqliteStore` (one has an argument and the other doesn't).

I can insert and read from the local toDoItems table. The issue is when trying to sync to the server. I have debugged it to the point of being able to report:

If I instantiate the store with empty arguments `MobileServiceSqliteStore()`, when trying to `push()`, I get an error: `tableDefinition cannot be null`.

If I instantiate the store with a parameter `MobileServiceSqliteStore('mobile.db')`, when trying to `push()`, I get an error: `Uncaught SyntaxError: Unexpected token < at file:///android_asset/www/index.html#side-menu/init:1`

In the first case, the error is generated directly in the error callback of the `push()` promise. In the latter case, the error callback does nothing - the promise seems to have been fulfilled - but the server shows no data, and the syntax error appears (not attributed to any line number in my code).

**Comment by markau** [comment]
I am using Cordova. My `config.xml` shows this version:
`<plugin name="cordova-plugin-ms-azure-mobile-apps" spec="~2.0.0-beta5" />`

The `AzureMobileServices.Cordova.js` library shows this in the header:
`v2.0.0-beta6-40613.155840`

**Comment by adrianhall** [comment]
Hi Mark - a few clarifications while waiting for the US to wake back up.
1) Is this only for Android or do other platforms suffer similarly?
2) Can you send us a read-out of all the versions you are using (including the cordova-cli)

Based on the syntax error, I think the server is returning HTML, which may mean it is sending an inappropriate error.  Can you add a diagnostic trace on the backend or a fiddler trace on the front end to actually capture the data?

While you are in the backend, can you also see if any errors are occurring?

Thanks,

**Comment by markau** [comment]
Hi Adrian, thanks. I suspect this is iOS as well, as whilst I can't see any errors in the XCode logs (despite the console plugin) it is hitting a wall, and I would guess its the same thing. 

I will need to get Fiddler working with Genymotion, or alternatively work out how to debug the backend in VS2015. I never quite got that worked out. 

I never considered the backend - do I need to do anything there to get the sync working?  Alternatively, could I have broken anything in the backend?

I created a table in SQL (with uniqueidentifier type on the id column).

**Comment by shrishrirang** [comment]
@markau The error `tableDefinition cannot be null` means that the store attempted to perform an operation on a table that is not defined using `defineTable`. This can happen for various reasons:

- You defined a table _t1_, inserted something in it, then changed the code and now you have got nothing to do with _t1_ so you don't define _t1_ anymore. However, because the store still has a log of all the operations you performed, it attempts to push the _t1_ changes when you do a push and fails as there is no definition for _t1_ now. Deleting the app and installing it again should fix this problem.
- Explicitly passing a different store name to the `MobileServiceSqliteStore` constructor will create a new store and hence you will not run into the above problem. This is what you are seeing in the second case you mentioned.

I will update the error handling to be more explicit about the error instead of simply failing with `tableDefinition cannot be null`.

To narrow down the issue, can you try the following:

1. Create a store instance with a name that you haven't used before. Or simply uninstall the app and install it again.
2. Now, insert just one record and attempt a push.

If this fails, most likely something is wrong in the client and a Fiddler log would help. Let us know what you see.

**Comment by markau** [comment]
OK, some progress!  

@shrishrirang you were right; I could see an old, invalid payload being POSTed to the tables/<tablename> end point. So, I am using a new store. 

@adrianhall is on to something too - HTML is being returned in the body - see below.

Please let me know if there is anything else I should try, or if you need further information.

HTTP/1.1 302 Redirect
Content-Length: 525
Content-Type: text/html; charset=UTF-8
Location: https://login.windows.net/**********/oauth2/authorize?response_type=id_token&redirect_uri=https%3A%2F%2F**********.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=**********&scope=openid+profile+email&response_mode=form_post&state=%2Ftables%2Fsynctest4&nonce=**********
Server: Microsoft-IIS/8.0
Set-Cookie: Nonce=**********; path=/; secure; HttpOnly
X-Powered-By: ASP.NET
Date: Mon, 11 Jul 2016 05:17:43 GMT

<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://login.windows.net/**********/oauth2/authorize?response_type=id_token&amp;redirect_uri=https%3A%2F%2F**********.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&amp;client_id=**********&amp;scope=openid+profile+email&amp;response_mode=form_post&amp;state=%2Ftables%2Fsynctest4&amp;nonce=**********">here</a></body>

**Comment by markau** [comment]
Can I just confirm the database schema - should it be:

id   uniqueidentifier
text   varchar(max)
complete  bit

OR 

id   uniqueidentifier
deleted  bit
version  varchar(max)
text   varchar(max)
complete  bit

FWIW, I am inserting data with this code:

````
  var insertData = function(item) {

    var newItem = {
      text: 'Fingers crossed...',
      complete: false
    };

    AzureService.table
    .insert(newItem)
        .done(function (insertedItem) {
            console.error(insertedItem.id);
            AzureService.syncContext.push();
        }, failure);

    function failure(msg) {
      console.error(msg);
    }
  }
````

**Comment by markau** [comment]
I can send the fiddler logs if you like. I don't imagine I should post them here with tokens etc.

**Comment by shrishrirang** [comment]
Looks like you have Easy Auth turned on. Try changing the backend URL from http://* to https://*. I am assuming you have performed `client.login(..)` before performing a push.

You'll only need the id, text, complete and version columns. You can drop the version column if you are not interested in conflict handling.

**Comment by markau** [comment]
I am using Express with Azure AD, but I don't recall the term Easy Auth. 

I have been using https for the client, i.e.

`AzureService.client = new WindowsAzure.MobileServiceClient('https://internationaltest.azurewebsites.net');`

**Comment by markau** [comment]
I am going to clean the code up, reset the emulator, and try to get back to square 1. I'll let you know how it goes. Thanks for the support.

**Comment by markau** [comment]
Back on track here. The push is failing with a new error message, I wonder whether you could shed some light on this?  #1 is raised by the pushHandler `onError` event, and #2 is from the error callback on the push() promise.

ERROR: {"isHandled":false} 

ERROR: data sync error: {"jse_shortmsg":"Push failed while pushing operation for tableName : synctest, action: insert, and record ID: fd942a31-3720-4e0a-b9c4-c6a92bbf4d36","jse_summary":"Push failed while pushing operation for tableName : synctest, action: insert, and record ID: fd942a31-3720-4e0a-b9c4-c6a92bbf4d36","message":"Push failed while pushing operation for tableName : synctest, action: insert, and record ID: fd942a31-3720-4e0a-b9c4-c6a92bbf4d36"}

Fiddler will no longer handle https traffic from Genymotion (tried a bunch of stuff including resetting Fiddler certificates) which is very frustrating as I can't provide further info right now.

**Comment by markau** [comment]
OK this is going well. Through becoming familiar with debugging the backend, and going back to basics and using the TodoItems, I have done a successful offline sync.  Very cool !

Thank you for all your help.
