### ISSUE TITLE
Login promise with federated AD doesn't resolve (or throw error)

### ISSUE THREAD

**Issue by markau** [Azure/azure-mobile-apps-js-client#165]
I have experienced this issue for quite some time with the Cordova client and our test O365 tenant. It is a problem on both iOS and Android. Sometimes it works, sometimes it doesn't - there seems to be no pattern to it.

Using the most simplest of examples, i.e:

```
        var client = new WindowsAzure.MobileServiceClient('https://mysite.azurewebsites.net');

        client.login('aad')
        .then(function (data) {
            console.error(JSON.stringify(data));
            if (data.userId) {
              console.error(JSON.stringify(data.userId));
            }
        }, 
        function(error) { 
          console.error(error); 
        });

```

With a clean InAppBrowser (i.e. first opening a window with clearcache=yes,clearsessioncache=yes options), this is what happens:
1. The MS login page always appears, and redirects to our on-site AD when I enter the username
2. The authentication always works
3. The GET to https://mysite.azuresites.net/.auth/login/aad?session_mode=token redirects to login.windows.net and then login.microsoftonline.com
4. The POST to  https://mysite.azuresites.net/.auth/login/aad/callback **times out** (http 500 error).  

At this point, the login() promise has not resolved, but also has not failed, so does not throw an error.  Therefore, the InAppBrowser remains open, with just a white screen showing.

If I then close the browser window (device back button) and click the button to repeat the process - eventually it will work (after up to 25-30 attempts).  Fortunately InAppBrowser caches the credentials.

When it works, I see the request:
1. GET to  https://mysite.azuresites.net/.auth/login/done

At this point, the InAppBrowser closes, the login() promise resolves, and all is well.

I can provide 3 sets of Fiddler logs to cover these scenarios - initial attempt, subsequent attempt (fail with timeout), and the eventual successful attempt.

Given how simple the example is, I can only assume the problem is one of authorisation, possibly between our federated AD and login.microsoft.online.  I hope the logs can highlight the issue (to someone who knows what they are looking for!)

**Comment by markau** [comment]
This doesn't seem to be a problem with my MSDN Azure subscription, so I can keep working. I will need to get this resolved to get people testing the app.  

Is this something we can do here, or do I need to raise an Azure support request?  Do you want to see the Fiddler logs in the first instance to know which way to go?

Thank you.

**Comment by adrianhall** [comment]
@markau Sorry for not tracking this.  We've been busy.

The fact that the server returns 500 means that there is something probably wrong with the configuration.  What do the server logs say on this?  Is this still an issue for you?

**Comment by elamalani** [comment]
@markau Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps).

I'll close this issue for now as it is almost 2 years old, but feel free to ask us questions if you have any. Thanks!
