### ISSUE TITLE
Pull() populates local store from database but with null properties (other than Id)

### ISSUE THREAD

**Issue by markau** [Azure/azure-mobile-apps-js-client#166]
* I have 4 rows in the Azure SQL database
* I create a local store and syncContext
* I insert a row into the store
* Push()
* Pull()
* The local store now has 5 objects. Each object has the correct Id from the database, however, all other properties are null -- **except for the object which was created locally**. 

Below is the contents of my store after a `Pull()` -- the bottom object is the one created locally.

````
[
{"FamilyName":null,"id":"4bb627ff62a845b99ce72b1c1df3339b","FirstName":null,"Citizenship":null,"DateOfBirth":null,"Comments":null,"UserId":null,"Email":null,"PhoneNumber":null,"SyncedToCRM":null,"LevelOfStudy":null,"ProgramCode":null},
{"FamilyName":null,"id":"71397216-a602-4079-be9c-3f14e0ce2edf","FirstName":null,"Citizenship":null,"DateOfBirth":null,"Comments":null,"UserId":null,"Email":null,"PhoneNumber":null,"SyncedToCRM":null,"LevelOfStudy":null,"ProgramCode":null},
{"FamilyName":null,"id":"db2f5400-dece-478b-9943-3a423e5ca872","FirstName":null,"Citizenship":null,"DateOfBirth":null,"Comments":null,"UserId":null,"Email":null,"PhoneNumber":null,"SyncedToCRM":null,"LevelOfStudy":null,"ProgramCode":null},
{"FamilyName":null,"id":"b2ac101c-604c-4d5e-a36d-56fa8bbd7b9e","FirstName":null,"Citizenship":null,"DateOfBirth":null,"Comments":null,"UserId":null,"Email":null,"PhoneNumber":null,"SyncedToCRM":null,"LevelOfStudy":null,"ProgramCode":null},
{"FamilyName":null,"id":"2afed522-b02b-4d6e-bc69-bf599dd945f2","FirstName":"Trevor","Citizenship":"Canadian","DateOfBirth":"01 Jan 1980","Comments":null,"UserId":"c20c287f091c17e9603a2b0c8510f1e0","Email":"trevor@sunnyvale.ca","PhoneNumber":null,"SyncedToCRM":false,"LevelOfStudy":null,"ProgramCode":null}
]
````

This occurs on both iOS and Android (Cordova client, beta5).

**Comment by shrishrirang** [comment]
Can you check what are the property values of those 5 records when you read them using the `MobileServiceTable.read()` method? Something like:

```
var table = client.getTable('TABLENAME');
table.read().then(function(result) {
   // Check properties of each record in result. Are they non-null?
});
```

**Comment by markau** [comment]
Yes, the direct `read()` brings back the properties as expected.

To expand on my initial comment (this doesn't add much, but thought it was worth mentioning):

* I used a new store - but this time did not insert a record into the store
* did a refresh (`push()` and `pull()`)
* the local table is populated with all rows, correct Ids, but all other properties are null

**Comment by shrishrirang** [comment]
Does the `push()` call before the `pull()` have any significance or do you get null properties even if you simply pull without pushing too? And is this specific to a particular table or are you seeing the same behavior for all table pulls? If you can grab the Fiddler logs when a pull is in progress that might be helpful.

**Comment by markau** [comment]
Erm.....  :grimacing:

My `store.defineTable.columnDefinitions` had, at some point, become camel case (like the database columns and backend property names) but of course, consistent with the doco, they should be lowercase in the client.

I humbly apologise for wasting your time!

**Comment by markau** [comment]
And the property names of the object being inserted into the store need to be lower case, consistent with the table definition.

This is all logical, but is it worth you ensuring all propery names are `toLower()` when the tablestore is being created?  Likewise, when inserting, ensure property names are lowercase?

To protect users from themselves :smile:

**Comment by shrishrirang** [comment]
Good to know you were able to get it working. Keep the feedback flowing.

https://github.com/Azure/azure-mobile-apps-js-client/commit/ee8bb89d7ec0b8b9567d7a771878d60f3b440d63 makes the store insensitive to table and column name case. The change will be available in the beta6 update.

**Comment by markau** [comment]
Ahh perfect, thanks. That will also solve what I further isolated the issue to - that CamelCase property names in my models (and by extension CamelCase column names created by EF) was actually a problem. "Citizenship" mapped ok to "citizenship" but "FirstName" did not map to "firstname", so I was still seeing nulls. It sounds like you are on top with beta6 though!  Cheers.
