### ISSUE TITLE
Convert PhoneGap Quickstart to Visual Studio and Cordova tooling

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#17]
The Cordova/PhoneGap QuickStart project should be a Visual Studio 2015 compatible project and flipped to use Cordova.

**Comment by phvannor** [comment]
This should probably go to -quickstarts repo and not here.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-quickstarts/commit/03dd4c4e87cf59f0ec85d25ac3b7bc6ccecd3056 closes this. The Quickstart is now a Cordova QS and can be launched as a VS project.
