### ISSUE TITLE
Should a push() prompt for a login if the user is not authenticated?

### ISSUE THREAD

**Issue by markau** [Azure/azure-mobile-apps-js-client#170]
We have to assume our users will not have Internet access at times.  So, I am enforcing a `client.login()` on only the initial run of the app, where users select a PIN for subsequent app access.  

Subsequent use of the app uses the local store. Any changes to the store will be followed by a `push()` and `pull()`, and these either succeed or fail depending on whether the user is logged in.  That's fine, however, I would expect the `push()` to prompt for a login if the user is not logged in - so that a login attempt can be made - and if the login fails, then that's OK, just try again next time.

Otherwise, in the present situation, I will need to explicitly call `client.login()` at some point, as a manual user task, so that any subsequent push() will work.  I suppose I can do that, but automatic is better.

I hope this makes sense.  To summarise:

* If I require a login() to proceed with use of the app, then push() and pull() will work - however if the login is not possible (no Internet connection) then the users are locked out of the app.  

* If I *don't* require a login() to proceed with use of the app, then no push() or pull() will work - forever ( unless i have a login button and remind them to login occasionally)

I therefore think that `push()` should at least attempt to have the user login - if not currently logged in, so that the `push()` will succeed if at all possible.

**Comment by markau** [comment]
Having given it some thought, I guess a "Click here to sync changes to the cloud" (which does a `client.login()` then `push()`) would actually not be too bad.  We could live with that. 

I would be interested in other opinions.

**Comment by shrishrirang** [comment]
Leaving `login` outside the scope of the `push()` operation is consistent with the behavior of the other APIs. Also, `login` would need to know which provider (Microsoft, Google, Facebook, AAD, Twitter) to use, so `push()` would need an extra argument for that, which is really something outside the scope of push.

**Comment by markau** [comment]
OK, that makes sense. 

I think also that until refresh tokens are fully implemented, having the user explicitly log in at their convenience, to initiate a sync, is going to be the cleanest way to go for our use case.
