### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-js-client#180]

**Comment by danderson00** [comment]
Detailed offline sync documentation should not be in readme. This should be moved to a separate blog post, MD file or github pages site.

The readme should contain a short description of how to get up and running with the client and include short code samples, i.e. basic usage and quickstart sections, similar to the node sdk readme.

**Comment by shrishrirang** [comment]
Noted. README is verbose in the short term till https://github.com/Azure/azure-mobile-apps-js-client/issues/21 is fixed.

**Comment by shrishrirang** [comment]
This is fixed now.
