### ISSUE TITLE
Add .npmignore

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-js-client#181]
Source is not currently intended to be consumed from a Node.js application and should be excluded - dist folder is all that should be included in the package.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/issues/158 and https://github.com/Azure/azure-mobile-apps-js-client/issues/88 are related issues. Plan is to stop bundling the code in the dist directory and instead make it possible to consume the repository as a nodejs package.

**Comment by danderson00** [comment]
Ahh... We should still package a built version so that web can consume it. We should also be updating the CDN, something we haven't done since 1.3.2. I can't remember exactly where it's located, I'll dig it up.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/pull/197 closes this.
