### ISSUE TITLE
Need valid package.json in root of repository

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#19]
In order for this repository to be made into a suitable repository for npmjs.org, bower and other package managers, we need a complete package.json in the root of the repository,  It's currently one step down.  In addition, the package.json file is missing key data:

- No description field
- No repository field
- No README data
- No license field

These need to be updated during the move.

**Comment by phvannor** [comment]
This will also require updates so that Visual Studio can still run the grunt tasks/etc when moved.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/commit/88ba26595e65d044c0e2a105a301f9e0b2098209 closes this
