### ISSUE TITLE
Cannot Include Client to Typescript

### ISSUE THREAD

**Issue by freshdev1** [Azure/azure-mobile-apps-js-client#190]
Hello All,
This is frustrating me a bit now. I am trying to use the Client in my Ionic 2 App. These are the steps I followed:

- I created working Ionic 2 App following the method at the Official Ionic 2 Website.
- I installed the JS SDK to the application following the step at [How to Use the JavaScript Client Library for Azure Mobile Apps](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-html-how-to-use-client-library/)
- Now when I add the following line:
> import * as WindowsAzure from 'azure-mobile-apps-client';
Typescript gives an error:
Error TS2307: Cannot find module 'azure-mobile-apps-client'

I don't know where I am creating problem. Can anybody guide me on this?

**Comment by SteveALee** [comment]
@freshdev1 

When you use the ```npm install 'azure-mobile-apps-client'``` npm installs the module in ```%projDir%/node_modules``` and when you ```import from 'azure-mobile-apps-client';``` the Typescript compiler needs to know where to look for modules. . The error indicates it's failing to find the module  so you should look for TS config options that define where it looks for modules. Perhaps in your tsconfig.json?

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
   ...
  }
}
```

**Comment by shrishrirang** [comment]
The article you are referring to is for using the Javascript SDK in browser / web applications. For using the Cordova SDK in your app, refer https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-cordova-how-to-use-client-library/ instead.

If you include the Azure Mobile Apps Cordova plugin as explained in the article, you won’t need to import the WindowsAzure namespace explicitly.

**Comment by freshdev1** [comment]
Thank you everybody. Luckily I got late to identify what @shrishrirang said above. But I still got it to work by following this work around:
http://ionicframework.com/docs/v2/faq/#adding-third-party-libs

I had to include in the typings in order to satisfy Typescript.

But I will now be following the cordova client now. As this appears to be the valid method of working with Ionic applications.
