### ISSUE TITLE
invokeApi fails with React Native on Android

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-js-client#193]
Due to using IframeTransport instead of DirectAjaxTransport - it calls into PostMessage.getOriginRoot, which in turn calls into parseUrl, which then attempts to create an element, but the DOM does not exist.

The solution to this is to make react native correctly use DirectAjaxTransport - the test at https://github.com/Azure/azure-mobile-apps-js-client/blob/master/sdk/src/Transports/DirectAjaxTransport.js#L17 is failing, i.e. global has not been defined before this is called.

**Comment by shrishrirang** [comment]
As React Native is not a supported platform yet, `invokeApi` failure is just one of many other issues. Let's use https://github.com/Azure/azure-mobile-apps-js-client/issues/195 to track the work to be done to add support for React Native.
