### ISSUE TITLE
update Cordova Google OAuth for pending WebView/InAppBrowser deprecation

### ISSUE THREAD

**Issue by rob3c** [Azure/azure-mobile-apps-js-client#194]
Hi, the Cordova client currently uses the InAppBrowser plugin for Google authentication, but Google is deprecating web views.
From the google developer blog: https://developers.googleblog.com/search/label/oauth

> With improved security and usability in mind, we will soon be ending the support for one of these ways. In the coming months, we will no longer allow OAuth requests to Google in embedded browsers known as “web-views”, such as the WebView UI element on Android and UIWebView/WKWebView on iOS, and equivalents on Windows and OS X.

Also, see the Ionic Framework blog about it: http://blog.ionic.io/google-oauth-changes/

> Starting October 20, 2016, if you’re using Google OAuth in a new app, and it’s presented through the InAppBrowser plugin, the OAuth request will be denied by Google. On April 20, 2017, all requests through InAppBrowser will be blocked.

It looks like the Cordova client needs updating to account for this, or things will start breaking soon.

Thanks in advance!

**Comment by danderson00** [comment]
We're reviewing the impact to all of our client SDK platforms at the moment. We'll keep you posted on the plans very soon.

Thanks for the link to the Ionic Framework blog!

**Comment by shrishrirang** [comment]
Implementation for this issue will be on the lines of https://github.com/Azure/azure-mobile-apps-ios-client/issues/90#issuecomment-256748256.

**Comment by idoMintzDev** [comment]
OK, login just stop working in my app!
getting the: disallowed_useragent (403) error!!!
My app running with Cordova/Android , is there no solution???

**Comment by pniko** [comment]
Hi @rob3c @idoMintzDev. Just wanted to let you know we are actively engaged in resolving this right now. Will update this thread further once I have an expected time frame for a fix to this.

**Comment by pniko** [comment]
Merged in #271 

Please let us know if you have any more issues. Thanks @rob3c and @idoMintzDev !
