### ISSUE TITLE
TypeScript Warning

### ISSUE THREAD

**Issue by jayeshanandani** [Azure/azure-mobile-apps-js-client#196]
Hi,

I am trying to use azure mobile apps with Ionic 2, Angular 2.

I followed this: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-cordova-how-to-use-client-library/

It installed Cordova plugin as per the command but now since its TS I will also need to install typings for same so the error goes away.

If I type import 'azure-mobile-apps-client' it says module not found. I am trying to implement the offline synchronization feature which is available after 2.0.0beta6 version. The file present at DefinetlyTyped is in beta 3 and in addition typings is unable to locate that file.

**Comment by jigarmistry** [comment]
Hello Jayesh,

You can use cordova plugin in Ionic2 without installing the typings for that plugin. Looks like typings are not available for this plugin. You do not need to import plugin as import 'azure-mobile-apps-client'

You can use this plugin as `window.cordova.plugins.WindowsAzure.MobileServiceClient("appurl");`

For this you need to install typings for cordova. After installing typings for cordova add path into main.d.ts file for cordova typings. After add following into index.d.ts file under cordova typings repo.

```
interface CordovaPlugins {
    diagnostic : any;
    WindowsAzure:any;
}
```

This should work. If anything please reply with error.

**Comment by rob3c** [comment]
@jayeshanandani There's actually an incomplete and slightly out-of-date type definition file already on DefinitelyTyped, but it's hard to find because it's called `azuremobileservicesclient` without the dashes in the name. Using the `typings` library, you should be able to install it as a global/ambient definition like this:
```
> typings install dt~azuremobileservicesclient --global
```
I used that as a base for creating my own version, which I'll try to publish when I can (making an official contribution to DefinitelyTyped is a bit of a hassle). In the meantime, you can just add entries with `any` types for anything typescript complains about (or add your own definitions, of course) while still leveraging the hints of what is there already.

**Comment by florianbepunkt** [comment]
I also try to use this with the last RC of Ionic. But none of the above suggested solutions work. Has this something to do with the latest changes in Ionic? When I follow this instruction https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-cordova-how-to-use-client-library/ I only get an undefined error: `error_handler.js:45EXCEPTION: Uncaught (in promise): ReferenceError: WindowsAzure is not defined`

**Comment by shrishrirang** [comment]
@jayeshanandani, We do not have official typings yet. It is on our backlog - refer https://github.com/Azure/azure-mobile-apps-js-client/issues/79.

@florianbepunkt, Refer the recommended resolution in https://github.com/Azure/azure-mobile-apps-cordova-client/issues/36 for the issue you reported.

Note that `WindowsAzure` will be available in the **global namespace** once the `devicready` event is fired and can be used as follows:
```
    var client = new WindowsAzure.MobileServiceClient('http://app-url');
```

Refer https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-cordova-how-to-use-client-library/ for detailed explanation.

**Comment by richardshergold** [comment]
@florianbepunkt I was just looking at using this with the latest RC of Ionic 2 myself.  Did you have any success with it?

**Comment by richardshergold** [comment]
@jayeshanandani  I was just looking at using this with the latest RC of Ionic 2 myself. Did you have any success with it?
