### ISSUE TITLE
Server directed login (Google) in IE can trigger small fixed popup

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#2]
(From azure-mobile-services#740)

Hi,

We have an issue with the Google OAuth popup when we trigger client.login('google') in Internet Explorer. The popup is fixed (no resizing possible) and there are no scrollbars. This happens if the original screen is small and when the original screen is maximized and the new screen is small (last known size). See below screenshot:

Google consent screen (not possible to accept):
![image](https://cloud.githubusercontent.com/assets/2187598/8549522/780e0106-24cb-11e5-86f3-626aa6d6b058.png)

This also is an issue when a user has to create a new account in this small popup. In Chrome it's possible to resize the popup, maximize screen and Chrome add scrollbars. In IE all these are not available. We use MobileServices.Web-1.2.7.min.js client library.

Regards,
Jeroen

Ref: @jeroencusters

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/pull/73 addresses this issue.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/commit/064203fae30780eb5f68023172ee064746b3fad8 closes this
