### ISSUE TITLE
Cannot Update server using `pushError.Update`

### ISSUE THREAD

**Issue by freshdev1** [Azure/azure-mobile-apps-js-client#200]
Hello Everybody,
I had been recently creating an App using Azure Mobile Cordova SDK. My application is build on Ionic 2. The Cordova Plugin is correctly configured and working as expected. Recently I had to implement the `conflict` scenarios. Currently there are only two scenarios that I am catering.

* If user selects the server copy checkbox, the local changes are discarded and server values are stored locally.
* If user selects the local copy checkbox, the local changes are `update` - d - on the server, and retained locally as well.

For the first scenario I run 
```
pushError.cancelAndUpdate(this.serverRecord).then((success) => {
	console.log("In Server copy success:");
	console.log(success);

	this.serverValueSaving = false;
	this.localValueSaving = false;
}, (error) => {
	console.log(error);
});
```
For the second scenario I am doing the following:
```
//this.clientRecord.Version = '';
pushError.update(this.clientRecord).then((success) => {
 
  console.log("In Server update success:");
  console.log(success);

  // pushError.isHandled = true;

  // console.log("Handled value:");
  // console.log(pushError.isHandled);

  this.serverValueSaving = false;
  this.localValueSaving = false;

}, (error) => {
  console.log(error);
});
```
In my understanding this should work and is pretty straight forward. But this does not work. I do get this `In Server update success:` in my console, but the values are not updated on the server, and the conflict is not understood as `handled` by the SDK.

PS:
I added `this.clientRecord.Version = '';` line, because when I tried to run the `PATCH` request through `POSTMAN` with the same payload I was getting `409 (Conflict)`, but if I removed the `Version` value, I got `HTTP OK 200` response. But this is also not working in the above code.

Please help! I am stuck badly! :worried:

**Comment by shrishrirang** [comment]
Hey @freshdev1, the sample at https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples demonstrates various conflict handling scenarios (use server value, use client value, use a custom value, etc). Specifically, [this](https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples/blob/38da82275c2d3e95bddc18f203d8539b185886f5/offline-sync-error-handling/www/js/tableManager.js#L62) is the conflict handler. You can implement your conflict handler on similar lines.

**Comment by freshdev1** [comment]
Thanks a lot for the prompt reply. I have left office by now. I did see the sample before, but when I got stuck with this problem the sample didn't come in my mind. :worried: !I believe this line in your sample was what I was missing:https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples/blob/38da82275c2d3e95bddc18f203d8539b185886f5/offline-sync-error-handling/www/js/tableManager.js#L108But again I believe a new bug should be logged. The SDK should give me some sort of error if this indeed was the problem. Will update you by tomorrow, when I try this at office.Thanks again for the help! :)                                                                                                                                                                                                   Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Shrirang ShirodkarSent: Wednesday, 21 September 2016 11:59 PMTo: Azure/azure-mobile-apps-js-clientReply To: Azure/azure-mobile-apps-js-clientCc: freshdev1; MentionSubject: Re: [Azure/azure-mobile-apps-js-client] Cannot Update server using `pushError.Update` (#200)Hey @freshdev1, the sample at https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples demonstrates various conflict handling scenarios (use server value, use client value, use a custom value, etc). Specifically, this is the conflict handler. You can implement your conflict handler on similar lines.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azure/azure-mobile-apps-js-client","title":"Azure/azure-mobile-apps-js-client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Azure/azure-mobile-apps-js-client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shrishrirang in #200: Hey @freshdev1, the sample at https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples demonstrates various conflict handling scenarios (use server value, use client value, use a custom value, etc). Specifically, [this](https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples/blob/38da82275c2d3e95bddc18f203d8539b185886f5/offline-sync-error-handling/www/js/tableManager.js#L62) is the conflict handler. You can implement your conflict handler on similar lines.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Azure/azure-mobile-apps-js-client/issues/200#issuecomment-248709061"}}}

**Comment by freshdev1** [comment]
This hasn't resolved the problem. The behavior is again the same as was happening before. :worried: It resolves the `update` promise to success, but nothing changes on the server, and get `undefined` in the `success` of the update promise. :worried:

My complete `onConflict` handler:
```
 public OnConflict(pushError) {
    console.log("In a conflict func:");
    console.log(pushError);

    console.log("Action of PUSH:");
    console.log(pushError.getAction());

    if (pushError.isConflict()) {
      var serverRecord = pushError.getServerRecord(),
        clientRecord = pushError.getClientRecord();

      if (serverRecord == undefined) {
        this._azureClient.getTable(pushError.getTableName())
          .where({ id: clientRecord.id })
          .read()
          .then((success) => {

            
            this.serverRecord = success[0];
            this.clientRecord = clientRecord;

            console.log(success);

            console.log("Server Record:");
            console.log(this.serverRecord);
            console.log("Client Records:");
            console.log(this.clientRecord);

            //Save server version and discard local values.
            if (this.serverValueSaving) {
              pushError.cancelAndUpdate(this.serverRecord).then((success) => {
                console.log("In Server copy success:");
                console.log(success);

                this.serverValueSaving = false;
                this.localValueSaving = false;
              }, (error) => {
                console.log(error);
              });
            }
            else if (this.localValueSaving) {
              console.log(this.clientRecord);

              this.clientRecord.Version = this.serverRecord.version;

              pushError.update(this.clientRecord).then((success) => {
                console.log("In Server update success:");
                console.log(success);

                this.serverValueSaving = false;
                this.localValueSaving = false;

              }, (error) => {
                console.log(error);
              });
            }


          }, (error) => {
            console.log(error);
          });
      }
      else {
        //We got the object from the server
        this.serverRecord = serverRecord;
        this.clientRecord = clientRecord;

        //Save server version and discard local values.
        if (this.serverValueSaving) {
          pushError.cancelAndUpdate(this.serverRecord).then((success) => {
            console.log("In Server copy success:");
            console.log(success);

            this.serverValueSaving = false;
            this.localValueSaving = false;
          }, (error) => {
            console.log(error);
          });
        }
        else if (this.localValueSaving) {
          console.log(this.clientRecord);

          this.clientRecord.Version = this.serverRecord.version;

          pushError.update(this.clientRecord).then((success) => {
            console.log("In Server update success:");
            console.log(success);

            this.serverValueSaving = false;
            this.localValueSaving = false;

          }, (error) => {
            console.log(error);
          });
        }

      }

    }

  }
```

**Comment by freshdev1** [comment]
Currently the project is just at the beginning state, I know some of the things are replication. I want to make things work and then cleanup the things. So do not pay attention to those things. :smile:

**Comment by shrishrirang** [comment]
`onConflict()` handler should return a promise that is resolved when the conflict resolution is complete. In your example, you should return a promise from `onConflict()` that is resolved when `pushError.update()` is resolved.  As your conflict handler does not return anything, the SDK assumes conflict resolution is complete even before it is actually complete. [Here](https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples/blob/38da82275c2d3e95bddc18f203d8539b185886f5/offline-sync-error-handling/www/js/tableManager.js#L109) is an example - note the `return` keyword.

Also, I suspect in your case the `push` method returns a promise that is resolved with the above conflict. [This](https://github.com/shrishrirang/azure-mobile-apps-cordova-client-samples/blob/38da82275c2d3e95bddc18f203d8539b185886f5/offline-sync-error-handling/www/js/tableManager.js#L179) is how you can check if that is inded the case.

If you return an appropriate promise from `onConflict`, `push` should complete successfully without any conflict.

If this does not help, please share the result of the `push()` call, i.e. how is the returned promise resolved / rejected.

**Comment by freshdev1** [comment]
@shrishrirang I will do as you said, due to some other assignments, I wasn't been able to test that.

This will give you an understanding about the version:
```
// ----------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved
// azure-mobile-apps-client - v2.0.0-beta6-40809.112219
// ----------------------------------------------------------------------------
```
:smile: hope that helps.

**Comment by freshdev1** [comment]
@shrishrirang well, I have updated my Implementation, and is now returning a `Promise`.

Promise Implementation:
```
public TestPromiseForUpdate() {
    return new Promise((resolve, reject) => {
      if (this.serverValueSaving)
        resolve("server");
      else if (this.localValueSaving) {
        resolve("client");
      }
    });
  }
```

`OnConflict` handler updated implementation:
```
 public OnConflict(pushError) {
   console.log("In a conflict func:");
    console.log(pushError);

    console.log("Action of PUSH:");
    console.log(pushError.getAction());

    var serverRecord = pushError.getServerRecord(),
      clientRecord = pushError.getClientRecord();
    var action = pushError.getAction();


    if (pushError.isConflict()) {
      var serverRecord = pushError.getServerRecord(),
        clientRecord = pushError.getClientRecord();

      if (serverRecord == undefined) {
        this._azureClient.getTable(pushError.getTableName())
          .where({ id: clientRecord.id })
          .read()
          .then((success) => {

            //Push the objects to the comparison array
            this.serverRecord = success[0];
            this.clientRecord = clientRecord;

            console.log(success);

            console.log("Server Record:");
            console.log(this.serverRecord);
            console.log("Client Records:");
            console.log(this.clientRecord);

            return this.TestPromiseForUpdate()
              .then((result) => {
                if (result === 'server') { // use the server value to resolve the conflict
                  return pushError.cancelAndUpdate(this.serverRecord);
                }

                if (result === 'client') { // use the client value to resolve the conflict

                  this.clientRecord.Version = this.serverRecord.version; // Update the version in the record to match the server version
                  
                  result = this.clientRecord;
                } 


                return pushError.update(result);
              }, (error) => {

              });
          }, (error) => {
            console.log(error);
          });
      }
      else {
        //We got the object from the server, so push object into the Array
        this.serverRecord = serverRecord;
        this.clientRecord = clientRecord;

        return this.TestPromiseForUpdate()
              .then((result) => {
                if (result === 'server') { // use the server value to resolve the conflict
                  return pushError.cancelAndUpdate(this.serverRecord);
                }

                if (result === 'client') { // use the client value to resolve the conflict

                  this.clientRecord.Version = this.serverRecord.version; // Update the version in the record to match the server version
                  
                  result = this.clientRecord;
                } 


                return pushError.update(result);
              }, (error) => {

              });
      }

    }

  }
```

**Comment by freshdev1** [comment]
@shrishrirang I believe I should open another Issue, because there is something wrong that's going on in the Cordova SDK. If there is a conflict in a `PATCH` request. The `pushError.getServerRecord()` does not return the server record. Where as it should. Why because if I see the response there is server object in it.

![Request](https://cloud.githubusercontent.com/assets/14213594/18835267/ab2b61c0-8413-11e6-8b80-8dd92ba7d131.PNG)

![Response](https://cloud.githubusercontent.com/assets/14213594/18835286/ce0d8d12-8413-11e6-92c5-ea02d3a0d3d5.PNG)

Can you make any sense of this to me?

**Comment by shrishrirang** [comment]
Regarding the first issue of the conflict handler not returning a promise, I can still see a code path that will return without returning a promise. Specifically, `this._azureClient.getTable(pushError.getTableName())` line doesn't have a `return` statement which means `return this.TestPromiseForUpdate()` won't be propagated to the caller of the `onConflict` callback. We need the SDK to know that `onConflict` is not complete.  

Besides, you don't really need `TestPromiseForUpdate` as `cancelAndUpdate()` returns a promise anyway. Give that a try and let me know if that helps.

Regarding the patch not returning server value:
- Can you share details of the conflict? i.e. server updated and client updated OR server deleted and client updated, etc? 
- What backend are you using: Node or .NET?
- Is your backend using SQlite or SQL server?

I am trying to understand the exact configuration when you see the backend returning the server record value and a 409 status code so that I can try it myself. My understanding is that if the status code is 409, you won't ever have the server record's value.

**Comment by freshdev1** [comment]
Ok, so there were two issues after which I was able to solve the issue.

- As @shrishrirang mentioned, I had code paths that were not returning `Promise`. I resolved this by adding the following:
```
if (this.serverValueSaving) { // use the server value to resolve the conflict
  return pushError.cancelAndUpdate(this.serverRecord);
}

else if (this.localValueSaving) { // use the client value to resolve the conflict

  this.clientRecord.Version = this.serverRecord.version; // Update the version in the record to match the server version
  return pushError.update(this.clientRecord);
  //result = this.clientRecord;
}

return new Promise((resolve, reject) => {
  resolve(x => {
	pushError.isHandled = false;
  });
});
```
So now there are no code paths that are not returning a Promise.

- I had been opening `store` at various pages, which resulted in that the `Version` field was missed from one definition. This was also causing problems.

So whoever get this error, I hope the above thread will give them a good sense of the issues they can face. A special thanks to @shrishrirang for helping me out on this issue, actively.

Lastly, I believe the documentations should be updated. As we do not have the documentation stating anything like, `OnConflict` should return a promise, and other things revealed by @shrishrirang above.

**Comment by freshdev1** [comment]
> Regarding the patch not returning server value:
> Can you share details of the conflict? i.e. server updated and client updated OR server deleted and client updated, etc?
    What backend are you using: Node or .NET?
    Is your backend using SQlite or SQL server?
 I am trying to understand the exact configuration when you see the backend returning the server record value and a 409 status code so that I can try it myself. My understanding is that if the status code is 409, you won't ever have the server record's value.

**Conflict Scenario**
- Client Updated in offline mode.
- Server Updated
- Client Made online
- Synchronized.... Bang! Conflict generated.

**Backend**
Backend is made on .NET and using SQL Server.

I have not been able to receive the server value currently from the SDK, since I have faced the above scenario as of now. But as I said above, my concern is that when I make a `PATCH` request from Postman, I am able to find the response of the server when the request completes with 409 conflict status.

**Comment by shrishrirang** [comment]
@freshdev1 - Opened https://github.com/Azure/azure-mobile-apps-js-client/issues/205 for the conflict issue. I am working on adding detailed documentation. This work is being tracked by https://github.com/Azure/azure-mobile-apps-js-client/issues/21
