### ISSUE TITLE
Pull Data change default orderBY "updatedAt"

### ISSUE THREAD

**Issue by Paul-Lo** [Azure/azure-mobile-apps-js-client#203]
Hi, 
I found that the default 
`syncContext.pull(new WindowsAzure.Query('todoitem' /* table name */));
`
will generate the following url to query backend controller

`$filter=(updatedAt ge datetimeoffset'1969-12-30T16:00:00.000Z')&$orderby=updatedAt`

Is there anyway we can define our own column in filter and orderby instead of using the default column "updatedAt" before we pull data?

Thanks.

* since I'm using Table Storage as backend db instead of SQL and Table Storage doesn't support "Order By", the above default pull with orderby behavior will return 'Query option 'OrderBy' is not allowed.

**Comment by adrianhall** [comment]
The filter that is generated is required for incremental sync.  You can remove the query completely to bring everything across each time.  You are right - table storage has some limitations that prevent its use in incremental sync scenarios.  This is one of the major reasons why we don't support table storage as an official domain manager.
