### ISSUE TITLE
pushError does not contain server record value

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-js-client#205]
Refer detailed comments by @freshdev1 in https://github.com/Azure/azure-mobile-apps-js-client/issues/200 about the client not reporting the server record's value in the even of a conflict / 409.

**Comment by shrishrirang** [comment]
Ok so here's the issue. The behavior of the server is different in the event of a conflict depending on whether or not the request contains the `If-Match` header.

If it _does_ contain the `If-Match` header, the response code is 412 and it _does not_ contain the server record.

If it _does not_ contain the `If-Match` header, the response code is 409 and it _does contain_ the server record.

This is not really a bug in the Cordova SDK. But it would be a good idea to have the server respond with the server record.

**Comment by shrishrirang** [comment]
@danderson00 - Any comments?

**Comment by adrianhall** [comment]
Is there any difference between the ASP.NET and Node backends, or are they the same?  (I'm hoping they are the same).

Also note that the definition of 409 pretty much means that we have to return the old record in the body, however there is no such reference in 412 in the spec.  Ref: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html 

I am also noting that 412 does not preclude us from returning the server record either.

**Comment by danderson00** [comment]
Unfortunately, there are subtle differences between how .NET and Node behave. Shrirang has a table of the differences. We need to make this consistent (there is an [issue](https://github.com/Azure/azure-mobile-apps-node/issues/497) for it). It's a matter of opinion whether we make Node like .NET or vice versa, I think we agreed to make Node match .NET? 

Regardless, it sounds reasonable to return the server record for both cases.

**Comment by adrianhall** [comment]
Agreed.  @shrishrirang - can you file a bug in each of the repos, then close this one?
