### ISSUE TITLE
PageSize in PullRequest isn't working

### ISSUE THREAD

**Issue by Sridhar4u2006** [Azure/azure-mobile-apps-js-client#206]
Hi, in the pullrequest the settings for pagesize is not working for me. I have mentioned the query, queryid and pullsettings as { pageSize: 1000}, but it is taking a long time to complete the pullrequest as it might be taking the default pageSize as 50. I have enabled the EnableQuery attribute to TableController method of the backend Service.

**Comment by shrishrirang** [comment]
Pull can take a long time to complete for various reasons (number of records, size of records, network speed to name a few). Can you install a filter using `withFilter()`, capture the request and response to see how many records are being requested and how many are being returned?

**Comment by Sridhar4u2006** [comment]
I have checked, I have requested 1000 and got 1000 with no delay but the delay is caused in inserting the retrieved records into Sqlite table. As per link http://www.sqlite.org/faq.html#q19 insert into Sqlite table without BEGIN and COMMIT will take longer time as each insert is its own transaction. 

So, is the transaction (BEGIN and COMMIT) maintained while inserting into Sqlite table after pull request?

**Comment by shrishrirang** [comment]
As of now, all the pulled records (1000 in your example) aren't batched and inserted in one go. So I can see scope for improvement by batching the inserts together.

Do you have any performance numbers that can show how long it takes to process a page (1000 records)? We can assume time spent between 2 successive outgoing requests is spent on local store operations.

If you have verified it `pageSize` works fine, can you update the issue title accordingly to reflect your performance complaint?

**Comment by shrishrirang** [comment]
@Sridhar4u2006 - As per your last comment, pageSize is working fine. I am closing this issue. If you have anything to report on performance, please update https://github.com/Azure/azure-mobile-apps-js-client/issues/211
