### ISSUE TITLE
Provide API documentation in gh-pages

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#21]
See @danderson00 for info on how he set up the Node SDK for this.

Need to provide jsdocs in the azure gh-pages.

**Comment by danderson00** [comment]
This should be a little more straightforward for the client due to its "type" based approach. jsdoc is more suited to this style of code. Feel free to hassle me!

**Comment by phvannor** [comment]
This would apply to all platforms, the public API should be identical across the 3 targets (with slight exceptions for push)

**Comment by danderson00** [comment]
I don't think we could get away with a single set of documentation though. There are, of course, subtle differences between platforms.

**Comment by phvannor** [comment]
Right, but I think we should add jsdoc style to all public functions initially and then we can discuss how they are exposed on gh-pages

**Comment by danderson00** [comment]
We've had a few people asking for TSDs for the Node SDK and it is looking likely that we will switch from jsdoc to TSDs. We need to do some more research, but we won't be doing both. I suggest we hold off on this and make the approach consistent for all JS components.

**Comment by shrishrirang** [comment]
API documentation is now available at http://azure.github.io/azure-mobile-apps-js-client/
