### ISSUE TITLE
Analyze performance of push and pull operations

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-js-client#211]
Refer discussion in https://github.com/Azure/azure-mobile-apps-js-client/issues/206 for more details.

**Comment by Sridhar4u2006** [comment]
The Pull operation for a table of 19 columns with no large data in any column, is taking approx of 4 min to complete 1000 records. So for my complete data of 7950 records the complete pull operation was taking an average of 25-30 mins.

**Comment by andreujuanc** [comment]
I did some insert tests, and it's true that each takes about a second each.

After some testing, it took on average 0.6 seconds to insert each one of the entries. (tested in Android emulator, local window app and my lumia 950), all gave similar results.

So certainly the insert is what is causing the bottleneck on pull operations.

I'll try to see how I can improve this and will show results.

This is my test code, in case I did something wrong:

```
var dataSize = 20;
        var inserted = 0;
        var start = Date.now();
        for (var i = 0; i < dataSize; i++) {
            var data = { text: i.toString() };
            //log('todoItemTable', todoItemTable);
            todoItemTable.insert(data)
                .then(function (a) {
                    inserted++;
                    if (inserted >= dataSize) {
                        var end = Date.now();
                        log('all inserted', (end - start)/1000);
                    }
                }, function (error) {
                    log('error', error);
                });
        }
```

**Comment by andreujuanc** [comment]
@shrishrirang , found one more issue, that makes sync slow.

Remember how inserts and deletes are being processed one by one on individual transactions?, well, this code is doing the same:
`operationTableManager.readPendingOperations(tableName, record[idPropertyName])`

For every pulled record, there is a read using a transaction for each operation there. Wonder if I can do the same here as for the upsert/delete.

**Comment by shrishrirang** [comment]
I am going to take a look at all store calls that can be batched. The one you mentioned is one such. Thanks for pointing it out. Let's use this issue to track all such instances and I will fix them all together.

**Comment by andreujuanc** [comment]
@shrishrirang Modified readPendingOperations and moved from 20 rows/s to 100 rows/s.
Just to confirm it is a big bottleneck there.
