### ISSUE TITLE
Pull error = "id is not valid"

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-js-client#217]
Hello, 
Scenario:
- Cordova and js client rc1
- One offline table.

My remote tables are empty and local are empty as well.

Push is completed without problems, but then pull gives me "id is not valid".

Is this a known issue?

**Comment by andreujuanc** [comment]
Dig deeper:

Insert statement:
`"INSERT OR IGNORE INTO CheckHistorico (id,deleted,NombreTarea,Realizada,IdActivo,FPeticion) VALUES (?,?,?,?,?,?)"`
Parameters:
`[6BB09950-7280-4286-B5F7-FEA9EF5F9730,0,Cambio electroválvula caja cambios,0,461,1465516800000]`

Update if more columns:
`[INSERT OR IGNORE INTO CheckHistorico (id,deleted,NombreTarea,Realizada,IdActivo,FPeticion) VALUES (?,?,?,?,?,?),UPDATE CheckHistorico SET deleted = ?,NombreTarea = ?,Realizada = ?,IdActivo = ?,FPeticion = ? WHERE id = ?]`

Parameters:
`[6BB09950-7280-4286-B5F7-FEA9EF5F9730,0,Cambio electroválvula caja cambios,0,461,1465516800000,0,Cambio electroválvula caja cambios,0,461,1465516800000,6BB09950-7280-4286-B5F7-FEA9EF5F9730]`

Looks fine but ends up in the error callback
```
 syncContext
            .pull(new WindowsAzure.Query('CheckHistorico'), 'checkhistorico_all')
            .then(function () {
                console.log('Syncing: Pull completed');
                callOnSyncStateChange(true);
            }, function (error) {
                callOnSyncStateChange(true);
                console.log('pull error', error);
            });
```


Im trying to get more into the code, i dont know if its a sqlite issue, or its something on the offline sync side.

I dont know where the error comes from, since im not knowledgeable with the code but saw this:
`transaction.executeSql(statements[i], parameters[i]);

How can i get a handled error if executeSql is missing both of success and error callbacks?

Thats why i still dont know who is throwing it.

Any help would be appreciated.`

**Comment by andreujuanc** [comment]
Ok, it was my fault. On delete records:
 **for (var i in ids) {
      if (! _.isNull(ids[i])) {
          Validate.isValidId(ids[i]);
      }
    }**
ids is an Array, and in my code i add a method to the prototype and its taking it into account, since code is iterating the properties as well.

I recommend change to simple for.

What you guys think?

**Comment by adrianhall** [comment]
Hi @andreujuanc 

Firstly, great that you got it working.

What precisely are you suggesting as the improvement?

**Comment by andreujuanc** [comment]
@adrianhall  
Thanks for fast reply.

The issue here is that (var i in ids) is not iterating but enumerating. And in this cases it will also include prototype members, where it shouldn't include them.

It's not a problem per-se, but I think this can cause troubles with anyone who just happened to add anything to the Array prototype.

Quick fix would be just `for (var i = 0; i < ids.length; i++) ` like here: https://jsfiddle.net/exfz89r8/2/

**Comment by adrianhall** [comment]
Is this in the quickstart code, or a sample you downloaded somewhere, or something you read in the docs (and if so, which doc)?

Thanks,

**Comment by andreujuanc** [comment]
It's in the project's source code:
https://github.com/Azure/azure-mobile-apps-js-client/blob/49b0c5b25e3ec939a30f127ac0cbac0225ebd5e0/sdk/src/Platform/cordova/MobileServiceSqliteStore.js#L351

**Comment by adrianhall** [comment]
Gotcha - that makes sense then.   Upgrading to bug.

**Comment by andreujuanc** [comment]
Great. Thanks.

**Comment by andreujuanc** [comment]
Ok, I just realized the issue is bigger than I thought.

I will remove the method in Array.prototype, since enumerations are used in lots of places on arrays (where it shouldn't be, i think) and is causing bigger problems than anticipated.

You may check here the use of enumerate:
https://github.com/Azure/azure-mobile-apps-js-client/search?utf8=%E2%9C%93&q=%22for+%28var+i+in%22&type=Code

Some are ok, because they are not arrays, and it makes sense to enumerate members of an instance, but when it's an array, its just better to iterate it.

Like I said before, i will remove my prototype (somehow) so I can continue using this client.

Sorry for being such a pain :)

PS: I think you may ignore my PR.
