### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-js-client#219]
Hello guys, 

Not related to https://github.com/Azure/azure-mobile-apps-js-client/issues/217 but i saw it when fixing it.

I found this:
```
if (Validate.isValidId(pulledRecord[idPropertyName])) {
     throw new Error('Pulled record does not have a valid ID');
}
```
Where the throw will never be executed, wince there is a throw inside the IsValidId method.

I think IsValidId should NOT throw exception, since the name has IS prefix, means that it should be bool.

On the other hand, if it should throw exception when id is not valid, then name should be different. Something like ThrowIfNotValidId or similar.

You may close this if you find it irrelevant. But i think clear code is key to success.

Cheers.

**Comment by shrishrirang** [comment]
You are right. This should be _.isValidId(..). Thanks for pointing that out.

**Comment by andreujuanc** [comment]
It's nothing. I find this project very interesting and i think i will use it in my next app.

I did notice it a bit slow, and saw that issue about performance.  Where we can talk about that? any chat room?

**Comment by adrianhall** [comment]
We don't have a chat room right now (like Gitter).  However, we are always looking at ways to improve performance.  I'd like to get something going where we look at "what is reasonable performance" and get some benchmarks before we actually put some guidelines in and/or actually suggest improvements.

**Comment by andreujuanc** [comment]
@adrianhall Alright. Sounds good.

For starters I think benchmarks should be done mostly on mobile devices, or at least really take them into account, not just do desktop tests, since this project is used in big part on phones and similar devices. This is key. Also platform and architecture.

We all know it's hard to do a benchmark on several devices, so there should be a place to compile all the data from different people. Can even be a github issue with some requirements to post into so does not get polluted, then a separate issue to comment and reference those benchmarks.

On the other hand, someone needs to choose a tools for benchmarking. Maybe Benchmark.js?

Also would be nice to get someone from Sqlite involved, for performance/optimisations on db operations.

**Comment by adrianhall** [comment]
@andreujuanc Let's open another issue on performance, rather than cluttering something that will be closed once the bug is fixed.
