### ISSUE TITLE
Node.js, Azure Mobile Sevices Client, JSDOM and WebJobs?

### ISSUE THREAD

**Issue by MarkBeharrell** [Azure/azure-mobile-apps-js-client#227]
Ok so im playing around with a webjob on my Azure platform and decided Id take a challenge and write it in JS.

I have essentially everything talking to an Azure Easy Tables that the app i'm writing relies upon - EXCEPT - I decided I wanted the server (Azure) to do some of the API heavy lifting for me and essentially grab and deposit info straight into the tables.

So far I can get a jsdom environment to talk to Azure but the user agent is kicking the Mobile client out.

```
var jsdom = require('jsdom');
var WindowsAzure = require('azure-mobile-apps-client');

jsdom.env({
  html: "<!DOCTYPE html><html><head></head><body></body></html>",
  done: function (errors, window) {
    var $ = require("jquery")(window);

    function filter(request, next, callback) {
      request.headers['User-Agent'] = "ZUMO/2.0";
      request.headers['User-Agent'] = '(lang=Managed; os=Windows; os_version=6.2.0.9200; arch=Win32NT; version=2.0.31217.0)';
      request.headers['X-ZUMO-VERSION'] = 'ZUMO/2.0 (lang=Managed; os=Windows; os_version=6.2.0.9200; arch=Win32NT; version=2.0.31217.0)';
      request.headers['ZUMO-API-VERSION'] = '2.0.0';
      request.headers['X-ZUMO-INSTALLATION-ID'] = 'xxxxxx';
      next(request, callback);
    }

    var client = new WindowsAzure.MobileServiceClient('https://app.azurewebsites.net');
    var locationTable = client.getTable('table');

    locationTable.read().then(
    function (success) {
      console.log(success);
    },
    function (fail) {
      console.log(fail);
    });

    console.log(client);
    console.log(locationTable);
    window.close();
  }
});
```

The window.navigator.userAgent reports:

`Node.js (win32; U; rv:v6.7.0) AppleWebKit/537.36 (KHTML, like Gecko)`

Azure connection to the table gives me this:

`Error: Unsupported browser - no suitable providers are available.`

Which when searched for implies that its triggering the Azure fail as it can't see any browser that will allow it to work.

I know it's got as far as the Azure platform as the `console.log(client)` responds with the installation ID.

As you can see i've was thinking it could be spoofed with a `withFilter` but no luck there.

So I'm hoping that the node.js install of the `azure-mobile-apps-client` can be allowed through. It's on the same server where the Easy Tables is and the rest of the Azure elements live so there shouldn't be any issues with security or connections in reality.

Mark

**Comment by adrianhall** [comment]
The azure-mobile-apps-client SDK does not work in Node.js.

For your particular scenario, just use the app setting to read the SQL database connection string and use node-mssql to do the work against the tables directly.  Your WebJob will have access.

If this answers your question, please close the issue

**Comment by MarkBeharrell** [comment]
Using the  node-mssql I've been successful with getting the heavy lifting done! Thank you! 

Obvs it's not as straightforward as the normal client version of the azure mobile library so it might still be worth looking into it at some point. 

The syntax is far easier on the client side and as such it feels more 'together' having this reproduced on the node.js and server side would further make it a more cohesive platform. 

Just my 2 pennies

Marm

**Comment by adrianhall** [comment]
Great to hear, Mark.  I'm going to close this.  We'll open up some specifics on the other side once we see what we need to do to support Node.js
