### ISSUE TITLE
Purge local table => Delete statement parameter limit

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-js-client#232]
If purge a table with more rows than the maximum amount of variables a statement can have there the purge fails with this error: "too many SQL variables". 

I think that if a purge should delete all rows. Maybe i'm missing something but doing reading all records and then deleting them with DELETE FROM table WHERE ID IN (<ids here>) wont work for medium sized and big applications.

Right now i need to sync 4857 rows, they will stay there, no much updating , but they are essential data for my logic.

Two options:

1.- when purging delete without WHERE. (risky?)
2.- doing this:  sqlite3_limit(db,SQLITE_LIMIT_SQL_LENGTH,size) ?? 

Will try to see if i can implement number 2 in client configuration.

Cheers

**Comment by adrianhall** [comment]
Can you please provide the code you are trying to use?

**Comment by andreujuanc** [comment]
@adrianhall Sure:

`syncContext.purge(new azure.Query('assets'))`

Data is already sync.

I literally followed the execution until here:
```
        var deleteStatement = _.format("DELETE FROM {0} WHERE {1} in ({2})", tableName, idPropertyName, deleteExpressions.join());
        if (this._editStatement) { // test hook
            deleteStatement = this._editStatement(deleteStatement);
        }
        transaction.executeSql(deleteStatement, deleteParams);
```

On my scenario, having 4000+ id's to delete exceeded the maximum statement size.

**Comment by andreujuanc** [comment]
Looks like the max limit can only be set in compilation time. I do not want to mess with sqlite code anymore :(

**Comment by shrishrirang** [comment]
Changing the list of IDs to a query should I'll take a look.

**Comment by andreujuanc** [comment]
@adrianhall @shrishrirang

More data: 
deleteStatement.length =>9747
4857 parameters.
Ids are 36 char each.
4857  * (36 +1 (comma) ) =174852 
174852 + 9747 = 184599 char long statement.

**Comment by andreujuanc** [comment]
Another option would be to "page" the id's to delete like it's done on sync operations.

**Comment by andreujuanc** [comment]
Maybe we can use sqlBatch ?

**Comment by andreujuanc** [comment]
Thanks!! gonna test this tomorrow. 

Great solution btw.!
