### ISSUE TITLE
Moved changes to new branch - Issue before PR

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-js-client#233]
I moved my change to another branch, since im more interested in this project than before. (and I hate working on master).

Before redoing PR , you guys can check it here: https://github.com/Azure/azure-mobile-apps-js-client/compare/master...andreujuanc:pull

Changes are:
1.- Simplify pullPage by moving stuff to processPulledRecords 
2.- Inside processPulledRecords I use a storeTaskRunner 
3.- Then for every record i call in a chain (called recordsChain) processSingleRecord where it's  checked against PendingOperations, id is validated, and "categorised" for delete or upsert.
4.- back in processPulledRecords after recordsChain is resolved I execute the records for delete and upsert.

Let me know if there is any other thing to comply with. Or any additional requirement. 

I tested this on my application and works good.  But i haven't done any unit test. yet.

**Comment by shrishrirang** [comment]
Thanks @andreujuanc for your implementation. I have your changes in my repository now - feel free to delete your pull branch if you want to. I'll do some testing and start a code review a little later.

**Comment by andreujuanc** [comment]
@shrishrirang Cheers
