### ISSUE TITLE
MobileServiceTable.read() returns incorrect error if table endpoint doesn't exist

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-js-client#242]
`table.where({complete: false}).read()` returns an incorrect error object if the table endpoint is missing. The error object is an HTML string when the unminified SDK bundle is used. Also, the error object is different when using the minified SDK bundle.

**Comment by shrishrirang** [comment]
@adrianhall - fyi.

**Comment by adrianhall** [comment]
thanks!
