### ISSUE TITLE
Feature Request: count

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-js-client#243]
Hello guys, happy new year!!

I have the not-so-urgent need of counting the local (offline) rows, and probably will implement it in the following months. But anyway i will drop here a FR, just in case somebody else knows how to do it better/faster, or just point me in the right direction.

I was thinking of using getSqlStatementsFromQuery to create a simple SELECT COUNT(1) FROM table

Ideas?

Cheers

**Comment by andreujuanc** [comment]
@adrianhall https://github.com/andreujuanc/azure-mobile-apps-js-client/blob/master/sdk/src/Platform/cordova/MobileServiceSqliteStore.js#L503

Still don't have tests for this, but it works. No idea if it's the best approach tho.
I have a page where I have to count using condition queries and it works 10 fold faster than result.length, specially on tables with more than 100 items.

**Comment by adrianhall** [comment]
Appreciate that.  Unfortunately, I am no longer at MSFT, and don't have the permissions to merge / change the code.  It will have to go back to the MSFT team.

**Comment by andreujuanc** [comment]
@adrianhall Sorry to hear that. :( 
Let's just wait to someone to check this. Since it's not so important, it's already in production on my fork. :)

**Comment by jwallra** [comment]
Hey @andreujuanc if you would make a PR against this repo we will review it.

**Comment by elamalani** [comment]
@andreujuanc Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). At this point, we are not adding new features to this product but please created a PR against this repo if you would like to add the support.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
