### ISSUE TITLE
Will this work with Angular 2 web, syncing?

### ISSUE THREAD

**Issue by chauey** [Azure/azure-mobile-apps-js-client#244]

**Comment by andreujuanc** [comment]
I did try it months ago before first angular release, when it was still beta.
Worked fine.

**Comment by adrianhall** [comment]
As long as you are not doing offline sync, everything works fine.  Offline sync is only available in the Cordova plugin due to its dependence on the SQLite plugin for Cordova.

**Comment by andreujuanc** [comment]
Right! I didn't read the "web" part and then the syncing edit. 

@chauey anyway you can implement a IndexDB Store to make sync work on browser. The client part wont have any issue since it's just JS.
