### ISSUE TITLE
Does web support offline data sync?

### ISSUE THREAD

**Issue by chauey** [Azure/azure-mobile-apps-js-client#246]
From the docs, it seems like offline data sync only works with cordova, not web. Is that so? If so, why and what advice to get this to work with Angular 2 web, mobile, and desktop app? Thx

**Comment by adrianhall** [comment]
technically, offline data sync is available for web as well - all you have to do is write an appropriate synctable implementation for the web.  WebSQL would probably work well here.

reality is that we haven't tried it.  We've just designed the interfaces appropriately to make it possible.  It isn't a functionality available "out of the box"

if you give it a go, then let us know how you get on.  We also accept pull requests if you want to donate your work to the (open source) project.
