### ISSUE TITLE
Push Notifications in Ionic 2 using Azure Mobile Apps and Azure Notification Hubs

### ISSUE THREAD

**Issue by paragw09ckp** [Azure/azure-mobile-apps-js-client#247]
I am developing an Ionic 2 app and implementing Push Notification functionality. In my Azure posrtal, I have successfully created a Mobile Apps Backend and a Notification Hub. I have connected both of them too.

On the client side (my Ionic 2 app), I have added plugin "cordova-plugin-ms-azure-mobile-apps" using the command:

ionic plugin add cordova-plugin-ms-azure-mobile-apps --save

This adds a <plugin> entry in my config.xml.

And in my code I am able to get hold of "WindowsAzure" in import statement and I have the following statement to connect to my Azure Mobile Apps backend:

this.pushClient = new WindowsAzure.MobileServiceClient('http://mymobileapp.azurewebsites.net');

Then, I have a function to register the device at an appropriate time (in ionViewDidLoad method) in which I have:

this.pushClient.push.register('gcm', handle, { "mytemplate": { "body": { "data": { "message": "{$(messageParam)}" } } } });

Now, when I run "ionic serve" command to run my app in browser window on my laptop I get the following error:

**Runtime Error
Cannot find module "cordova-plugin-ms-azure-mobile-apps"**

The stack is:

`Error: Cannot find module "cordova-plugin-ms-azure-mobile-apps"
    at Object.<anonymous> (http://localhost:8100/build/main.js:114800:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29990:72)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:114542:79)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:29966:82)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:114262:71)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)`

I have looked around a lot to get some pointers but no thing is available. :(

Any idea on why this is happening? How I can fix this?

I would highly appreciate if you can please help me fix this.

Thank you!

**Comment by shrishrirang** [comment]
Try using the following commands instead for running your app in browser:

```
ionic platform add browser
ionic run browser
```

**Comment by paragw09ckp** [comment]
Hi @shrishrirang - thanks for your prompt reply, very much appreciated!

Ran the commands you mentioned. Now, it tries to open the app in a completely new browser window. However, I am still getting a white blank screen with the following output on my console:

`200 /index.html (gzip)

200 /cordova.js (gzip)

200 /build/polyfills.js (gzip)

200 /build/main.css (gzip)

200 /cordova_plugins.js (gzip)

200 /plugins/cordova-plugin-device/www/device.js (gzip)
200 /plugins/cordova-plugin-device/src/browser/DeviceProxy.js (gzip)
200 /plugins/cordova-plugin-inappbrowser/www/inappbrowser.js (gzip)
200 /plugins/cordova-plugin-inappbrowser/src/browser/InAppBrowserProxy.js (gzip)
200 /plugins/cordova-sqlite-storage/www/SQLitePlugin.js (gzip)

200 /plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.Ext.js

200 /plugins/cordova-plugin-splashscreen/src/browser/SplashScreenProxy.js (gzip)

200 /plugins/cordova-plugin-splashscreen/www/splashscreen.js (gzip)

200 /plugins/cordova-plugin-statusbar/www/statusbar.js (gzip)

200 /plugins/cordova-plugin-statusbar/src/browser/StatusBarProxy.js (gzip)

200 /plugins/ionic-plugin-keyboard/www/browser/keyboard.js

200 /plugins/cordova-plugin-ms-azure-mobile-apps/www/MobileServices.Cordova.js (gzip)

200 /config.xml (gzip)

404 /screen

200 /build/main.js (gzip)
`

The "404 /screen" is in red. So, 404 means it's not able to get that resource. Is it? I am not sure what that "/screen" is and what I need to do about it? Would appreciate if you could please give some suggestion or perhaps a fix. I have already spent a lot of time on this, trying all sorts of things. :(

**Comment by shrishrirang** [comment]
I would suggest you to run your app for the browser platform without the cordova-plugin-ms-azure-mobile-apps plugin first to make sure your app is ok. If everything is ok, add the plugin and then try again. From what you have shared so far, it appears to me to be an issue specific to your app rather than the plugin.

**Comment by paragw09ckp** [comment]
That's exactly what I was trying. :)

And it did work fine (on regular browser, android phone and the browser platform that you asked me to add) before I added the cordova-plugin-ms-azure-mobile-apps plugin.

Then I added the plugin and after writing the corresponding code, tried running the app again. It did not work on regular browser as well as the browser platform that you asked me to add. Did not try on android phone.

Please do let me know if you want me to try anything else.

**Comment by shrishrirang** [comment]
Can you share a standalone app on Github? I'll take a look.

**Comment by paragw09ckp** [comment]
I have shared a link with you. Please confirm once you receive it as I am trying this link sharing for the first time. Thanks.

**Comment by paragw09ckp** [comment]
I came across this link and thought of sharing with you. Not sure what to make out of it. Here is the link:

https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps

There is a "Try it out" link to test this library:

https://runkit.com/npm/cordova-plugin-ms-azure-mobile-apps

On running the test on the above URL, it shows the same error that I am getting. That is, 

Error: Cannot find module 'cordova-plugin-ms-azure-mobile-apps'

Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/17579929/22578909/3d8d48c6-e99a-11e6-8758-6825ed3feb19.png)

**Comment by paragw09ckp** [comment]
Hi @shrishrirang - just wanted to touch-base with you and check if had a breakthrough.

Going by the search result and looking around on this issue, it does look like I am probably the first person to face it. :(

Please do let me know if I can help in any way to get it fixed.

Thanks!

**Comment by shrishrirang** [comment]
I don't think the 'try it yourself' link works for Cordova plugins.

**Comment by paragw09ckp** [comment]
Oh, you mean the one on runkit.com, I see. I got the same error as what I am getting when I run my Ionic 2 app so thought of sharing with you.

**Comment by shrishrirang** [comment]
I verified that the plugin works fine with ionic v1 and v2. Here are steps to add the plugin to a hello world ionic project for your reference.

```
# Create a hello world ionic v2 project
ionic start ionicv2 --v2
cd ionicv2

# Add the Cordova plugin
ionic plugin add cordova-plugin-ms-azure-mobile-apps

# Add the following 3 lines to app.component.ts
declare var WindowsAzure: any;
var client = new WindowsAzure.MobileServiceClient("https://shrirs-demo.azurewebsites.net");
window.alert("MobileServiceClient instance: " + client);

# Build and run for browser
ionic platform add browser
ionic run browser
```

**Comment by paragw09ckp** [comment]
:100: :+1: :1st_place_medal: 

Oh my goodness, so that was the solution! I am glad I contacted you and then Abdul otherwise there is no way in the world I would have figured it out on my own.

**Nowhere** in the Azure Mobile Apps documentation or this particular plugin's reference it is mentioned that one need to use it in that fashion...the way you said!

Thanks a lot to you and Abdul to keep looking into this with such patience. I really appreciate it very highly!

Now I can enjoy my weekend! :)

You too have a great weekend!

**Comment by adrianhall** [comment]
I'll get this added to our HOWTO document!

**Comment by paragw09ckp** [comment]
That would be perfect, Adrian. :) Thanks!

**Comment by abhishek-krishna** [comment]
# Create a hello world ionic v2 project
ionic start ionicv2 --v2
cd ionicv2

# Add the Cordova plugin
ionic plugin add cordova-plugin-ms-azure-mobile-apps

# Add the following 3 lines to app.component.ts
declare var WindowsAzure: any;
var client = new WindowsAzure.MobileServiceClient("https://yoursitename.azurewebsites.net");
window.alert("MobileServiceClient instance: " + client);



After the above steps, how to use the reference of **client** in another **.ts** file?

**Comment by Karthikaivel** [comment]
Thank you.This is useful information for learner's.
