### ISSUE TITLE
[E2ETest] Fix / redesign e2e tests

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-mobile-apps-js-client#25]

**Comment by phvannor** [comment]
Can we fill in the details of what this means?  Its unclear what this would cover?

**Comment by danderson00** [comment]
We haven't agreed on that yet. I have a draft email that explains my thinking around this, I'll send it through soon.

**Comment by shrishrirang** [comment]
@danderson00 - What exactly is this issue tracking?

**Comment by danderson00** [comment]
haha to fix / redesign the E2E tests. They are not in an optimum state, but it's hard to justify the effort if they're all passing.

**Comment by shrishrirang** [comment]
One of the many things that need to be fixed
- It should be easy to run end to end tests for browser using the js-client npm package, for browser using the browserified bundle and for Cordova, with locally generated build or a custom build (given an build location). https://github.com/Azure/azure-mobile-apps-js-client/blob/master/e2etest/scripts/setup.js does part of this, but it is cumbersome. Need to streamline the whole thing.
