### ISSUE TITLE
No error on incorrect column type name

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-mobile-apps-js-client#250]
As title suggest, I made a mistake and wrote 'data' instead of 'date' and there was no error when the table was altered.

```
define([], function () {
    return {
        name: 'OtsCapturas',
        columnDefinitions: {
            id: 'string',
            RealDate: 'date',
            Comments: 'string',
            InputDate: 'data' // HERE,
            deleted: 'boolean',
            createdAt: 'date',
            updatedAt: 'date'
        },
        direction: 'push'
    };
});
```

There was no error, not even when creating or altering the table. It does fails when serialization process kicks right before inserts/update an item.

I think it should at least log a message in console. 

Cheers.

**Comment by elamalani** [comment]
@andreujuanc  Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). At this point, we are not fixing bugs in the SDK unless it's a critical issue.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
