### ISSUE TITLE
.vscode directory is not ignored

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#251]
VS Code leaves behind a directory - need to add it to .gitignore

**Comment by danderson00** [comment]
Agh! Why? It's useful to include the .vscode folder. We should undo this change.

**Comment by adrianhall** [comment]
The .vscode folder is not useful at all.  It's a local user-implementation folder.  Ignoring it ensures we don't leak private stuff out and ensures non-pollution of the source code.  Happy to discuss tomorrow.

**Comment by danderson00** [comment]
That's not entirely correct. The .vscode folder also contains launch.json - the configuration for launching and testing your code which is generally not user specific. It's time consuming to have to recreate launch.json on each machine. 

We could probably just include that one file, but I generally don't end up with anything else in that folder anyway. Thinking about it, this folder also contains things like project specific configuration (indentation style, etc.).
