### ISSUE TITLE
Encryption to SQLite

### ISSUE THREAD

**Issue by kkocabiyik** [Azure/azure-mobile-apps-js-client#257]
As far as I search over the sdk I couldn't find anything about encryption. It is good to have an encryption for sqlite connections to protect to data on local.

**Comment by adrianhall** [comment]
The JS Client does not support encryption for SQLite.  There is a great blog post on using encryption on SQLite for the .NET Client.

**Comment by khowling** [comment]
Would be great to have an encrypted client store in the cordova client out-of-the-box with the Azure mobile SDK
