### ISSUE TITLE
Possible VS2017 issue

### ISSUE THREAD

**Issue by schroe2a** [Azure/azure-mobile-apps-js-client#259]
After installing VS2017 and creating a new project, I added this plugin to my project.  This plugin adds "cordova-sqlite-storage" as a dependancy, but adds version 1.5 which itself does not support Visual Studio 2017.  According to their git hub site they have created version 2.* which supports VS2017.
I needed remove and re-add the sqlite plugin.  If there is any easy way to make the default experience in VS2017 work right away, that would be nice.

**Comment by adrianhall** [comment]
We'll update the cordova-sqlite-storage dependency on the next release if it passes all the tests.

**Comment by elamalani** [comment]
@schroe2a Are you still running into this issue? We released the latest Cordova plugin last month. Please update your application to use it. I'll close this issue for now but feel free to contact us in case you have any questions.
