### ISSUE TITLE
Plugin makes the build so large you can't use MacInCloud remotebuild as described in docs

### ISSUE THREAD

**Issue by schroe2a** [Azure/azure-mobile-apps-js-client#260]
I'm hoping I'm wrong on this one...
It appears that after adding this plugin to my project I'm no longer to build on iOS with the MacInCloud solution because the request to build times out (about 90 seconds) before it can upload the build .tgz file.  I hope I'm doing something wrong or there is a way to increase the timeout on the VS TACO side, but as is it seems this plugin prevents support of iOS cloud remotebuild scenarios?

**Comment by andreujuanc** [comment]
Try referencing the js (prebuild ones) and adding sqlite storage plugin manually.

**Comment by adrianhall** [comment]
I'm surprised by this (and there is very little we can do about it, hence the closure).  Azure Mobile Apps SDK is a relatively small SDK.  Esprima (which is a sub-dependency) is large, but Azure Mobile Apps is hardly the culprit here.  Sorry - but you need to take this up with MacInCloud.
