### ISSUE TITLE
Localhost

### ISSUE THREAD

**Issue by carnould** [Azure/azure-mobile-apps-js-client#261]
I just installed the Azure Mobile Apps Server from:
https://github.com/Azure/azure-mobile-apps-net-server

Then follow these instructions to configure the server:
https://docs.microsoft.com/fr-fr/azure/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk
And to get the WEBSITE_AUTH_SIGNING_KEY:
https://github.com/Azure/azure-mobile-apps-net-server/wiki/Local-development-and-debugging-the-Mobile-App-.NET-server-backend

I created a new Asp.Net MVC Web Application and Added in Index.cshtml:
<script src="https://zumo.blob.core.windows.net/sdk/azure-mobile-apps-client.min.js"></script>
<script>
    debugger;
    var client = WindowsAzure.MobileServiceClient("http://localhost:31476/");
    var table = client.getTable("Person");
    debugger;

</script>

Client stay undefined.

Can you help to fix this error?

Other question:
Is it possible to find a simple sample running in Localhost With : 
- Windows Mobile App Authentication Server
- Client using Javascript to logging

Thank you for you help

**Comment by adrianhall** [comment]
You need to wrap it in an onready event handler.

**Comment by elamalani** [comment]
@carnould We haven't heard back from you. I am closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
