### ISSUE TITLE
Support for handling/encrypting cookies while authenticating

### ISSUE THREAD

**Issue by ThorConzales** [Azure/azure-mobile-apps-js-client#266]
By default cookies are stored without any encryption in Android and iOS. This is a significant security flaw since malicious users can easily access that store if the device is lost, or when the device is rooted then other apps could also read cookies that they should have no access to. Having access to cookies would grant them power to impersonate the victim and access other services that also use Azure AD.

Would it be possible to make sure cookies are not persisted in the default storage and provide methods for developers to read and write cookies so they could store them encrypted somewhere else other than webview's default unencrypted cookie store. Currently most of the cookies have httponly flat set so it is not possible to read cookies grammatically with S without modifying AAD backend to send back those cookies without httponly flag or find a way to send back cookies some other way that can be read, which should be a special case, only if the developer is willing to implement the secure storage on their own.

I propose to add an additional parameter in auth method to pass in all the necessary cookies that are needed to continue authenticating without prompting the user to re-enter credentials (such as ESTSAUTHPERSISTENT, ESTSAUTH, ESTSAUTHLIGHT and other that are required). And to provide a callback function which will return all the cookies that the developer should persist on their own when the authentication succeeds.

**Comment by ThorConzales** [comment]
Managed to solve the issue on my own.

**Comment by jnevins-gcm** [comment]
How did you solve? We also are looking for an programmatic way of getting these cookies
