### ISSUE TITLE
Bulk Insert - Enhancement

### ISSUE THREAD

**Issue by shah-smit** [Azure/azure-mobile-apps-js-client#267]
I am using this library
`<script src="//zumo.blob.core.windows.net/sdk/azure-mobile-apps-client.2.0.0.js"></script>`

And this is the service, that is calling insert.
```
addSubjectSpecialization(specialization): Promise<any>{
        var orderTable = this.client.getTable("specialization");
        return new Promise((resolve, reject) => {
            orderTable.insert(specialization).then((res) => {
                resolve(res);
            }, (err) => reject(err))
        })
    }
```

In my component I am doing a foreach, to insert multiple objects. Is there any better way? That means: Instead of foreach, do we have a function for bulk insert?

**Comment by elamalani** [comment]
@shah-smit Sorry for the super late reply on this issue. Were you able to solve this?

**Comment by elamalani** [comment]
I will close this issue for now as we haven't heard back from you. Feel free to contact us in case you have any questions.
