### ISSUE TITLE
MobileServiceSqliteStore: Store Initialization throwing error

### ISSUE THREAD

**Issue by keshav2k5** [Azure/azure-mobile-apps-js-client#268]
I am trying to use the Azure mobile apps cordova plugin to implement offline sync on my app (following the instructions over here https://github.com/Azure/azure-mobile-apps-js-client)

`import * as WindowsAzure from 'azure-mobile-apps-client';`

` var client = new WindowsAzure.MobileServiceClient('http://xxxxx.azurewebsites.net');`
`
  var store = new WindowsAzure.MobileServiceSqliteStore('local.db');
`

When i initialize store App throwing runtime error:

`
__WEBPACK_IMPORTED_MODULE_5_azure_mobile_apps_client___default.a.MobileServiceSqliteStore is not a constructor`

how to fix this solve this issue

**Comment by chumana** [comment]
😢 same here

**Comment by keshav2k5** [comment]
I run this in emulator/device it didn't throw any error, MobileServiceSqliteStore won't work in the browser. sorry for the late reply.
