### ISSUE TITLE
How do I remove the updatedAt query

### ISSUE THREAD

**Issue by Yanayaya** [Azure/azure-mobile-apps-js-client#269]
I have a cross platform mobile app built using Xamarin Forms and Visual Studio, it uses an Azure Mobile App table api to get its data. What I noticed was that the backend seems to run an additional query for incremental sync which checks the updatedAt columns timestamp.

Can you tell me where the query is generated (or what file holds it) within the node.js backend on Azure or rather, how I can remove it? It's a condition that we don't need as it's generating ghost data in the apps listview which is making everything appear as incorrect.

To clarify the node.js backend mobile app was automatically generated on Azure using Easy Tables within the Mobile App configuration (https://blog.xamarin.com/getting-started-azure-mobile-apps-easy-tables/). You simply add the name of your table and it will add the version, deleted, updatedAt and createdAt columns to the table for you.

It's an odd one but I feel totally out of control with my data, the app I made is ready only so the end user never deletes or updates anything.

**Comment by andreujuanc** [comment]
Xamarin? I think you need to go to this repo: https://github.com/Azure/azure-mobile-apps-net-client
Or NodeJs backend: https://github.com/Azure/azure-mobile-apps-node

**This one is for javascript client.**

Anyways it's better if you keep those column names tho. I have few business apps, one of them with 200 tables of which I offline sync about 35 of them. I have my own updatedAt columns which are named updatedDate, so I keep deleted, updatedAt and so on, for this mechanism , and my own columns for my app. That way you have lot's of control of when the row should update or not (just controlling the update in the trigger).

Anyway, if you want to know how the query is generated from the backend to sql server, head over the second link which will take you to that repo.

Cheers

**Comment by elamalani** [comment]
@Yanayaya Sorry for the late follow up on this issue. Were you able to remove the updatedAt query?

**Comment by elamalani** [comment]
We haven't heard back from you. I am closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
