### ISSUE TITLE
Is it possible to use offline sync in the browser with sql.js?

### ISSUE THREAD

**Issue by aronmek** [Azure/azure-mobile-apps-js-client#273]
How would i go about configuring the sync context to use sql.js?
For those who don't know [sql.js is sqlite compiled to js with emscripten.](https://github.com/kripken/sql.js)

**Comment by MatkovIvan** [comment]
Hi,

Sorry for late response.
No, this is an unsupported case for this SDK.
This mentioned in the [README](https://github.com/Azure/azure-mobile-apps-js-client#support):
> Offline Sync is only supported in Apache Cordova situations.

Best,
Ivan

**Comment by andreujuanc** [comment]
IIRC, you can implement it. Look at the current sqlite implementation: https://github.com/Azure/azure-mobile-apps-js-client/blob/master/sdk/src/Platform/cordova/MobileServiceSqliteStore.js

I was about to start to do it but some other project came in.

This client is very easy to modify and alter to your needs.

Play around with it, its internals are very interesting, tho , great part of it should be rewritten with a different approach.

**Comment by elamalani** [comment]
@aronmek Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). At this point, we are not adding new features in this product.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
