### ISSUE TITLE
Timestamp displaying invalid date in mozilla and Edge.

### ISSUE THREAD

**Issue by sujeetjaiswara** [Azure/azure-mobile-apps-js-client#277]
![image](https://user-images.githubusercontent.com/3294327/43586756-0f3e88be-9686-11e8-8e24-a66d38dffe35.png)

**Comment by dhei** [comment]
Hi @sujeetjaiswara,

Thanks for getting in touch. 
Can you provide some context of this issue? Are you using Azure Mobile Apps on Cordova? What is the reproduce steps of your issue?

**Comment by sujeetjaiswara** [comment]
I am using vanilla js.

function successD(rs) {
    let obj = rs;
    console.log(rs[0].lastAccessed);
}

getRecords();
function getRecords() {
    table
        .read()
        .then(successD, failure);
}

**Comment by andreujuanc** [comment]
What's the table definition for the table? Can you share a reproducible demo?

**Comment by andreujuanc** [comment]
Can I see students table declaration?

**Comment by sujeetjaiswara** [comment]
@andreujuanc  You mean table in azure portal ?

**Comment by andreujuanc** [comment]
Oh sorry, you are not using the sync functionality. I thought you were. 
Let me see if I can repro that on my side.

**Comment by dhei** [comment]
@sujeetjaiswara, in case you haven't seen it yet, I recommend following Azure Mobile Apps [get started doc](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-cordova-get-started) and [How to use Apache Cordova client library doc ](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-cordova-how-to-use-client-library). Please share detailed repro steps of your issue.

**Comment by sujeetjaiswara** [comment]
Hi @dhei
I am using following doc for my app.
[https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-html-how-to-use-client-library](url)

**Comment by sujeetjaiswara** [comment]
@dhei and @andreujuanc

I just returned plain text in "tryParseIsoDateString()" function then i get desired  results.(timestamp). 
I think, problem in "tryParseIsoDateString" function. Could you fix this ?

```javascript
exports.tryParseIsoDateString = function (text) {
    return text; /* For debugging purpose. (sujeet)  */

    /// <summary>
    /// Try to parse an ISO date string.
    /// </summary>
    /// <param name="text" type="String">The text to parse.</param>
    /// <returns type="Date">The parsed Date or null.</returns>

    Validate.isString(text);

**Comment by jwallra** [comment]
So, if I understand correctly, this is a workaround that you've implemented and you get the desired results?  If you're happy with that I would continue using the workaround.  If you think these is a bug in our SDK then you're welcome to make a PR.

**Comment by sujeetjaiswara** [comment]
@jwallra 
In chrome, i am getting correct timestamp.

**Comment by andreujuanc** [comment]
This should be cover by a test. @sujeetjaiswara can you cline the project, run the unit tests in ur machine and see if they pass? Might be some localization issue.

**Comment by sujeetjaiswara** [comment]
@andreujuanc 
I am using `2018-07-21 08:31:05.623` & `2018-07-23T09:31:18.82Z` timestamp.

**Comment by sujeetjaiswara** [comment]
@here 
I fixed this issue after update of following line:

```javascript
// Matches an ISO date and separates out the fractional part of the seconds
// because IE < 10 has quirks parsing fractional seconds
// var isoDateRegex = /^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d*))?Z$/;
var isoDateRegex = /(\d{4})-(\d{2})-(\d{2})T(\d{2})\:(\d{2})\:(\d{2})[+-](\d{2})\:(\d{2})/; //(fixed for mozila & edge browser)

**Comment by jwallra** [comment]
Thanks @sujeetjaiswara for your help!  I'll close the issue now :)

**Comment by sujeetjaiswara** [comment]
@jwallra 
Could you commit this fixed applied in your `cdn` library ?

**Comment by MatkovIvan** [comment]
@sujeetjaiswara Actually, the regex above doesn't looks correct. The groups are changed and that broke usage in the code below.
