### ISSUE TITLE
How we could use wild card searching?

### ISSUE THREAD

**Issue by sujeetjaiswara** [Azure/azure-mobile-apps-js-client#279]
@here 
I want to get result using wild card searching (i.e. Like %term%)

**Comment by dhei** [comment]
As far as I know, there's no built-in to do wild card search like you described. Which backend (.NET / Node.js) do you use? For Node.js backend, the supported query methods can be found at http://azure.github.io/azure-mobile-apps-node/module-queryjs_Query.html. It should be the same case for .NET backend.

**Comment by dhei** [comment]
@sujeetjaiswara, I am not sure if I understand you. What does your query mean? Can you elaborate on that?

**Comment by sujeetjaiswara** [comment]
@dhei 

I am trying to execute query like:
```sql
SELECT * FROM students WHERE Name LIKE 'a%'

**Comment by dhei** [comment]
@sujeetjaiswara,

There is no built-in support of "LIKE" clause here. If you want to do string matching in the where clause, you can use something like `indexOf` function like in [this ](https://stackoverflow.com/a/22485334/873234)example.
