### ISSUE TITLE
getting error Unsupported Expression Null -- create-react-app only when I Build

### ISSUE THREAD

**Issue by samjross** [Azure/azure-mobile-apps-js-client#283]
I have a file, `azure.js`, which looks like this:

```
import axios from 'axios';

const azApi = require('azure-mobile-apps-client');


const azureFilter = (request, next, callback) => {
    if (localStorage.propertyToken) {
        request.headers['auth-token'] = localStorage.propertyToken;
    }

    next(request, callback);
};

const client = new azApi.MobileServiceClient('/').withFilter(azureFilter);

const tables = {
    propertyFiles: client.getTable('Properties_PropertyFiles')
};

const azure = {
    propertyFiles: {
        getFilesForProperty: (propertyId, page) => {
            return tables.propertyFiles.where({property_id: propertyId}).orderByDescending('createdAt').skip(20*(page-1)).take(20).read();
        },
    }
};

export default azure;
```

This is a file that I'm using in a create-react-app app. Now this function, `azure.propertyFiles.getFilesForProperty()` works absolutely perfectly when I run the create-react-app test server, `npm run start`, but when I build it and put it on my server, it starts giving me the error `Unsupported Expression Null`

Now what's extra weird is that other azure-mobile-apps-client apis work -- if I were to do something like 

`return table.propertyFiles.read(`&$filter=property_id eq '${propertyId}'`)` that would work, I have other parts of my api that run perfectly. 

I just took another of my apis, that was in the above format, `.read(odata)`, and I changed it to the `where({}).read()` format, and it broke again, but again only when I build, not when I run the create-react-app test server.

I'm slightly concerned that the problem might be that I'm requiring the azure-mobile-apps-client, rather than importing it, but I couldn't get import to work for some reason.

**Comment by samjross** [comment]
Just posting an update --

I modified my create-react-app to put this link to the library right in the header:

`<script src="https://zumo.blob.core.windows.net/sdk/azure-mobile-apps-client.2.0.1.js"></script>`

and modified my `azure.js` file to look like this:

```
//const client = new azApi.MobileServiceClient('/').withFilter(azureFilter);
const client = new window.WindowsAzure.MobileServiceClient('/').withFilter(azureFilter);
```

And now the api, with the `where({}).read()`, works perfectly well

**Comment by jwallra** [comment]
Glad you figured it out!  Thanks for posting the follow-up :)

**Comment by samjross** [comment]
Well I don't feel like I 'figured it out'. That's a workaround, not a solution. I don't want to put the library in the header like that, I want to use it like I'd use any other npm module - with 'import' preferrably.

`import azureClient from 'azure-mobile-apps-client'`
