### ISSUE TITLE
Not able to register device on notification hub : Ionic3

### ISSUE THREAD

**Issue by abhishek3999** [Azure/azure-mobile-apps-js-client#284]
Hi,
I have followed following steps:
I was trying implement push notification with ionic3: 
1. Created firebase project to get google-services.json,sender id and legacy server key.
2. Installed push plugin ionic3
3. Installed cordova-plugin-ms-azure-mobile-apps
4. To send device token to server,referred method initPushNotification from `https://medium.com/@ankushaggarwal/push-notifications-in-ionic-2-658461108c59` this document .
5. On Azure portal,created new mobile app.Reffered `https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-cordova-get-started`. skipped 1 and 2 step under quick start.
6. followed steps for creating notification hub:-> *Configure a notification hub* steps from
: `https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-android-push-notification-google-fcm-get-started`
7. ionic cordova build android
8. Installed application on a device.
9. Got registeration Id (handler from FCM) success message of registered  (‘gcm’,registration id).
10. While sending Test send push notification from Azure portal,could not match found.(sent notification successfully 0:passed,0:failed)
11. Push notification could not received on a device. (edited)
Still I am suffering through issue.Verified GCM stored API key[legacy server key by firebase]

Please help me out.
Thank you in advance.

**Comment by bmourat** [comment]
Hi @abhishek3999 

To investigate your issue could you provide a code snippet of your push registration process and your config.xml file.

Thanks,
Murat

**Comment by abhishek3999** [comment]
Hi,

I have provided used code snippet and config.xml file.
Please find it.

Thanks,
Abhishek3999

**Comment by bmourat** [comment]
@abhishek3999 
Do you get correct `data.registrationId` in `registration` event ? Cause i'm reading [instructions](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md) for push plugin and it seems like `SENDER_ID`parameter has been removed and instead you need to put your google-services.json in config file.

**Comment by abhishek3999** [comment]
@bmourat 
I am getting registration id.sending 
` 
 this.client = new WindowsAzure.MobileServiceClient('http://selfpush.azurewebsites.net');
this.client.push.register('gcm', data.registrationId, {
        mytemplate: { body: { data: { message: "{$(messageParam)}" } } }
    });`
By this azure registration had not done on server.Checked by sending `Test send`.
0:passed 0:failed
What would be reason?

**Comment by abhishek3999** [comment]
Hi,

I have kept google- services.json file in platform/Android/app folder.may
that's reason I got registration Id.
What would be reason?
Please let me know.

Thanks

**Comment by bmourat** [comment]
Hi @abhishek3999 
What do you mean you have kept `google-services.json` file in platform/Android/app folder? Where is your file now and did you add it to the config file as stated in the documentation? While i'm investigating this issue, please have a look at the documentation on setting up pushes on Cordova. maybe you'll find something.

**Comment by abhishek3999** [comment]
Okay.

**Comment by bmourat** [comment]
Hi @abhishek3999 
Could you please add a `callback` parameter to `register` method call, like this:
```
```

**Comment by bmourat** [comment]
Hi @abhishek3999 
Could you please add a `callback` parameter to `register` method call, like in snippet below, and see if there are any errors:
```
this.client.push.register(
  'gcm', 
  data.registrationId, 
  {
    mytemplate: { body: { data: { message: "{$(messageParam)}" } } }
  }, 
  null, 
  function(error, response) {
    if (error) {
      console.error('Error registering for pushes: ' + error);
    } else {
      console.log('Registering for pushes response: ' + response.statusText);
    }
  }
);
```

**Comment by abhishek3999** [comment]
Hi,
I have used above code snippet.getting error as `unexpected connection failure `
actuallly I had used npm package `azure-mobile-apps-client`.
Where is missing my thread?

**Comment by abhishek3999** [comment]
Please reply on same.

**Comment by bmourat** [comment]
Hi @abhishek3999 

I've created a [sample app](https://github.com/bmourat/ionic-azure-push) for you, that demonstrates how to register for pushes. Please add you `SENDER_ID` and change endpoint address and see if it will work with you endpoint. If not, this means that your notification hub setup is not complete.

Best,
Murat

**Comment by abhishek3999** [comment]
Hi bmourat,

Perfect. It is working fine when I ran into the browser.`ionic cordova run browser`Registered successfully. But a single error throwing as **error: subscribing for push notifications**.
And on actual device **1.error: subscribing for push notifications
2.error: Unexpected connection failure.**
I would like to ask you that how did you include google-services.json file in the app and how did you configure?

**Comment by bmourat** [comment]
I've copied `google-services.json` to `platforms\android\app` folder and that seems to be all i've done.

**Comment by abhishek3999** [comment]
Same I did.
My Env. state:
cordova android version used - 7.1.1 
In config xml file changed id that what I had used registering in firebase for google-services.json.
Could you please tell me where I am a missing point?

**Comment by abhishek3999** [comment]
Yes.I got registration ID.

**Comment by abhishek3999** [comment]
yes.
configured notification service for GCM just added API key[legacy server key].

**Comment by abhishek3999** [comment]
Hi,

Have you completed all steps in backend creation app.I mean to say that at backend followed stps are:
1. create mobile application
2.notification hub and resource 
3. create a new cordova app with 3steps are in this.
I have skipped 1st and 2nd because of database.
4.Configure with API key.
I would like to you ask that are the all steps in creating cordova app backend necessary?

**Comment by bmourat** [comment]
Hi,
Do you have Authentication Service turned off? 

![screenshot 2018-10-29 at 07 49 54](https://user-images.githubusercontent.com/833045/47629980-503eea80-db4f-11e8-929f-52e61416efa0.png)

Could you please provide your server side logs? To collect them you need to enable logging in the `Diagnostic logs` section, like below:

![screenshot 2018-10-29 at 07 52 21](https://user-images.githubusercontent.com/833045/47630025-9dbb5780-db4f-11e8-9ac8-4d6c254416aa.png)

Now you can go to `Log stream` and select `Application logs`

![screenshot 2018-10-29 at 07 53 16](https://user-images.githubusercontent.com/833045/47630058-c8a5ab80-db4f-11e8-9cd7-ff6485106127.png)

**Comment by bmourat** [comment]
Hi @abhishek3999 

Were you able to collect logs during device registration?

**Comment by abhishek3999** [comment]
No.no more logs found.
Actually I am failing in database connection.

**Comment by abhishek3999** [comment]
Yes. thanks for the cooperating with this issue.the problem was about
database connection.
