### ISSUE TITLE
Authentication with providers stopped working

### ISSUE THREAD

**Issue by PaulARoy** [Azure/azure-mobile-apps-js-client#287]
Provider auth (facebook, twitter, google at least) are no longer working, neither on production or development. There has been no change on front-end but I constantly get the following error on auth:

```ERROR TypeError: Cannot set property 'mobileServiceAuthenticationToken' of undefined```

Has there been any change on server-side that has not been reviewed for JS client?
I post this issue here because mobile SDKs still seem to work.

Thanks!

**Comment by PaulARoy** [comment]
I did a diagnostic from bundle js file (not minified)

What I found on line https://github.com/Azure/azure-mobile-apps-js-client/blob/master/sdk/src/LoginUis/BrowserPopup.js#L68

`evt.data` value is `{"type":"LoginCompleted","oauth":{}}`
Whatever the provider is, oauth value is empty; we're supposed to have token informations here!

This is completely blocking in production and probably not on the right repo: could you tell me where to report this bug to fix it asap?

Thanks!

**Comment by dhei** [comment]
Hi @PaulARoy,

Sorry to hear this. Based on your description, it looks like it could be something may have changed on App Service backend. 

If you have an azure support plan, could you open a support ticket from Azure portal to report this issue? If you can prepare steps to repro your issue to the support team, that would definitely help.

Thanks.

**Comment by dhei** [comment]
@PaulARoy, could you share the repro steps with a sample app (like a quickstart app) of this issue here?

**Comment by PaulARoy** [comment]
Hi @dhei, Azure Support just gave me a one-time ticket for support plan. I'll keep you updated on the issue but I don't have the time right now to make a full repro project with both front-end & back-end.

Thank you very much for your answer!

**Comment by alexrysgspr** [comment]
Same goes with me. I can't authenticate anymore. 

azure-mobile-apps-client.min.js:21 Uncaught TypeError: Cannot set property 'mobileServiceAuthenticationToken' of undefined

**Comment by izerbib** [comment]
@PaulARoy @dhei We are seeing the same issue on production. Our sign up / login flow is completely down right now. Any update on that?

**Comment by PaulARoy** [comment]
@izerbib None at this time. Ticket is opened for 16h now. 

Glad to see I'm not the only one, even though I'm sorry you're experiencing the same issue !

**Comment by izerbib** [comment]
@PaulARoy I'm currently speaking with their engineers / product team. They are working on it currently.

**Comment by PaulARoy** [comment]
@izerbib Perfect! Keep us updated if you have anything (I'll do the same).

**Comment by jcbrooks92** [comment]
@PaulARoy can you share your case number so I can link it with the investigation we ongoing.

**Comment by PaulARoy** [comment]
The support Request ID is 119020722002401

**Comment by cgillum** [comment]
Just FYI, the Azure App Service engineering team is actively investigating this to see if it could be related to a recent change.

**Comment by cgillum** [comment]
We believe this is a regression caused by a recent Azure App Service update. We have a fix in place which will be rolled out in the next few hours. Once the fix is rolled out, it will require the app backend to be restarted. I'll post back when the update has been rolled out.

**Comment by PaulARoy** [comment]
I'm sorry, as I said to @jcbrooks92 by mail, the issue remains unfixed this morning, even with a backend restart.

**Comment by PaulARoy** [comment]
The problem was resolved this week-end by the Azure team
