### ISSUE TITLE
FCM push notification not work

### ISSUE THREAD

**Issue by yuhaii** [Azure/azure-mobile-apps-js-client#289]
We find that following code doesn't work for FCM:

this.client.push.register('fcm', theToken, {

We checked the SDK change log https://github.com/Azure/azure-mobile-apps-js-client/blob/master/CHANGELOG.md . It supports GCM on v1.2.5. But I didn’t see it supporting FCM in this change log.

![image](https://user-images.githubusercontent.com/39817657/56555796-8f16a000-65c8-11e9-95a4-2bdb5e3439d1.png)

I also checked its source code. The SDK have testing code for GCM and it dosen’t have testing code for FCM. It seems like azure-mobile-apps-js-client SDK dose not support FCM. 

![image](https://user-images.githubusercontent.com/39817657/56555812-9b026200-65c8-11e9-8c11-3e96384a6c1b.png)

May I know whether azure-mobile-apps-js-client SDK  support FCM? If not, do we have plan to add this feature?

Thanks!

**Comment by Jamminroot** [comment]
Hi @yuhaii,

We are not adding new features to the product. Please refer to the SDK readme that highlights the future of Azure Mobile Apps.

Thanks,
Dmitrii

**Comment by andreujuanc** [comment]
You don't need this library in order to use push notifications and/or azure notifications hub. :)
