### ISSUE TITLE
The .gitignore in the generated directory causes issues with npm local install

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#3]
(From: azure-mobile-services#540)

The `.gitignore` file in the javascript `src/generated/` directory is picked up by npm when doing an `npm install` from the git repository file.  This means that generated files are not copied over as part of the npm install.  I'm using npm install to pull the files into a separate project as part of the build process:

```cmd
cd myproject
npm install ../azure-mobile-services/sdk/javascript
```

By adding an `.npmignore` to the root of `azure-mobile-services/sdk/javascript/` the generated files can be added to the local npm package. This will override the `.gitignore` settings (although it will be ignored by `npm install`).

Ref: @joewood

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/pull/72 addresses this

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/commit/88ba26595e65d044c0e2a105a301f9e0b2098209 closes this
