### ISSUE TITLE
Update master branch to bundle javascript files using browserify

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-js-client#39]
We want to do away with the in house bundler and instead start using browserify

**Comment by phvannor** [comment]
This should impact all platforms, not just browser.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/commit/0bbc06dd681b21c5d1b550413b54c4e066baa049 closes issue https://github.com/Azure/azure-mobile-apps-js-client/issues/39
