### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-js-client#43]
Will this package be installable from **npm**?

**Comment by adrianhall** [comment]
Hello Joe,

Yes, we absolutely will be publishing this package tp npmjs.org, so that it is installable via npm

**Comment by phvannor** [comment]
Is there a different tracking issue to publish to NPM?  That we can link to here?

**Comment by adrianhall** [comment]
No - any more than there is a tracking issue to publish for Node or .NET - it's just a part of the regular release cycle.

**Comment by phvannor** [comment]
I guess I don't follow, isn't there work involved to make this consumable via npm (at least new artifacts), not to mention pulling in the localization logic into here so the built file is identical to the one on the CDN and  the copy published on NPM for Cordova?

I have tracking issues for CocoaPods/etc on iOS, so I'd expect the same here.

**Comment by adrianhall** [comment]
Good point - I will add a task specifically for that.
