### ISSUE TITLE
Provide publish mechanism for npm

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#47]
Update release process so that the JS client can be consumed using npm install (npm publication) - this is separate from the cordova build release process.

Update release docs to reflect any process changes.

**Comment by joewood** [comment]
Any ETA for the npm package? Will it be CommonJS compatible?

**Comment by shrishrirang** [comment]
With https://github.com/Azure/azure-mobile-apps-js-client/pull/72 the Javascript client for Mobile Apps can be installed as an npm package.

The client will be available as a standalone distribution file. The distribution file is built using browserify prior to publishing the package. Use of browserify aliases needs to be done away with to get to 100% CommonJS compliance.

**Comment by shrishrirang** [comment]
https://www.npmjs.com/package/azure-mobile-apps-client beta4 is now available on npm.
