### ISSUE TITLE
Test impact of cookie returned by EasyAuth (Client-Directed Auth Flow)

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#5]
Is there a cookie in the client directed flow?
does it get stuck to the session requests?
how does it interact with future client or server login flows.

Ref: @phvannor

**Comment by shrishrirang** [comment]
Commit f8469065199e6314e4c85c8f1699ee87ea32cd2b closes #5
- Login requests now contain the session_mode=token query string. This essentially tells EA to only return the auth token and not cookie.
