### ISSUE TITLE
Support A+/Promise

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-js-client#50]
This library seems to use WinJS.Promise rather than taking a dependency on a polyfill library (e.g. es6-promise).  I've always understood that there are compatible issues with the WinJS implementation in that resolved promises are called back synchronously instead of asynchronously (which is spec).  This would cause compatible issues, especially with native provided promises (which all evergreen browsers support now). 

Any plans to switch this to a polyfill?

**Comment by adrianhall** [comment]
Adjusting this to say "Support A+/Promise" - which is in essence deprecating the WinJS promise capability (since we are deprecating WinJS support) and updating the library to utilize an A+/Promise library like bluebird: https://www.npmjs.com/package/bluebird

**Comment by andreujuanc** [comment]
👍 for bluebird

**Comment by elamalani** [comment]
@joewood Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). At this point, we are not adding new features to this product.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
