### ISSUE TITLE
Fix login using Live SDK token

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-js-client#53]
- Attempting a login using a token obtained from Live SDK fails with error 403: 'You don't have permission to view this directory or page'
- This is applicable to WinJS and Cordova/WinJS (basically, wherever Live SDK is supported)

**Comment by phvannor** [comment]
I think this is set up?  I've seen no issue on iOS with OneDrive, and this looks like the error you get if you give the wrong token up.

**Comment by shrishrirang** [comment]
It's possible that just the tests are broken and need to be fixed. Either way, this can be used to track getting the tests running.

**Comment by phvannor** [comment]
Yeah, you may have older code that was using "authenticationToken", whereas (From what I can tell) newer OneDrive SDKs only give you the access token, so you need to use "access_token"

**Comment by shrishrirang** [comment]
@phvannor - Yeah, you were right. It was just 'access_token'

**Comment by shrishrirang** [comment]
Commit f8469065199e6314e4c85c8f1699ee87ea32cd2b fixes this issue.
