### ISSUE TITLE
Declining application authorization during facebook login puts client into bad state

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps-js-client#56]
See https://github.com/Azure/azure-mobile-services/issues/738 for full description. 

The original issue was reported for managed WP8.1 but a customer indicated the issue exists for JS client too. We could start by trying to reproduce in cordova.

**Comment by shrishrirang** [comment]
Reopening this. Verify this once in browser before closing it.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/commit/1f68419ec7bb7c9e282e07bc66f08128aaad5a2c closes this
