### ISSUE TITLE
GCM registration failures due to unsafe header error

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-mobile-apps-js-client#57]
See https://github.com/Azure/azure-mobile-services/issues/711.

This may changes on in the server SDKs or perhaps with the platform level CORS functionality, but tracking here since it impacts Cordova customers.

**Comment by phvannor** [comment]
Its affects all native consumers as well.

**Comment by phvannor** [comment]
'Location' header is part of Registration APIs, the newer Installation APIs we consume from NH no longer requiring accessing this header.

**Comment by b3na** [comment]
I have the same error and i am in version 1.2.8. I am trying to connect a Cordova/Ionic app. So I which version is this solver? 
And in order to use version 2 do I have to migrate from Mobile Services to App Service? I am confused with this. Thanks

**Comment by phvannor** [comment]
you need to configure CORS on your server to always return the 'Location' as an allowed header.  If using a .Net Service that is pretty easy, if using Node it gets more complicated (as Node echoes what you ask for, so you must actually make the client ask to be able to access Location first)
