### ISSUE TITLE
Login does not prompt for credentials when using InAppBrowser

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-js-client#59]
- Once successfully logged in, subsequent login calls do not prompt for credentials (even after a logout) on android, iOS, WP 8.
- Only way to work around this is re-installing the application.
- Note that this is even after calling EA login with session_mode=token query string. 
- Need to clear the past session cookies (provider's cookies) while launching in-appbrowser's login window. InAppBrowser's clearsessioncache/clearcache option (https://github.com/apache/cordova-plugin-inappbrowser) might help.

**Comment by shrishrirang** [comment]
Clearing the cache as mentioned in the earlier comment is not a good idea as it will affect other scenarios too that depend on cookies for their functioning.

**Comment by phvannor** [comment]
Of note EA Logout currently doesn't do anything with provider's other than AAD.  (And it doesn't have any impact on the X-ZUMO-AUTH token, so at this point there is no reason to try to use it)

Dealing with provider's cookies is tricky, as some flows (like FB's remember me) you may want to keep...  So it may ultimately need switches the dev can control.

**Comment by shrishrirang** [comment]
There is not much that can be done here. Clearing InAppBrowser's cookie cache will fix this problem but will have a side effect of clearing all cookies. Using client authentication flow will be the best solution to avoid this issue.
