### ISSUE TITLE
Support Easy Auth in Browser and Cordova Ripple environment

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-js-client#60]
- The browser popup flow needs to be fixed.

**Comment by joewood** [comment]
Is this issue why client driven login from a browser is broken for Mobile Apps with the current build?

**Comment by phvannor** [comment]
I believe these are mainly focused on the server driven auth flows.

**Comment by phvannor** [comment]
The client driven flows should be breaking primarily only due to CORS setup, which should now be available via the portal for a web app or you can configure manually in your app code as well.  @shrishrirang would have the details.

**Comment by joewood** [comment]
Using the current master of this repo against a cloud hosted mobile app doesn't work if I call `login("facebook")`. The facebook login dialog is launched as a pop-up, but not closed when complete. The **promise** is never resolved. The promise *is* canceled if I cancel the dialog.  CORS doesn't apply here as the login is initiated from the same origin (this is a dual web/mobile app endpoint).

Is this related to this issue, or should I raise a separate issue?

**Comment by phvannor** [comment]
Ok, that is what we refer to as the server directed flow.  The popup communication (via postMessage) has not yet been fixed.  That is what this issue is tracking I believe.

**Comment by joewood** [comment]
OK, great. Thanks.

**Comment by phvannor** [comment]
So its clearer in the issue: Currently the server's final redirect in EA (/done) only sends back the token in the querystring.  Our popup based JS login methods, require the final page on the server to stream back some JS that uses postMessage to send that back to the parent window.  As such, the client needs to use the EA redirect querystring param to have the last page be a page server by our Server SDK that does that work.  So there are 2 more related issues to have the server SDKs host & server that final redirect page as well.

**Comment by shrishrirang** [comment]
This is fixed in the beta4 release of https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps and https://www.npmjs.com/package/azure-mobile-apps-client
