### ISSUE TITLE
SPIKE: Figure out the design for the pop-up server-directed auth flow

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#7]
Result: Additional work items in JS Clinet, Node Server and Net Server projects to support design

Supported Browsers:
  IE 10
  IE 11
  Firefox latest
  Chrome latest
  Edge

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/commit/6a1eca4fd7fc6170b0fb0e61375bc4f0a644ebdb fixes server directed login flow in browsers.
