### ISSUE TITLE
How to use Javascript client SDK on HTML? 

### ISSUE THREAD

**Issue by Seichis** [Azure/azure-mobile-apps-js-client#76]
Is there any documentation available or shall I take a deep dive into the SDK?

**Comment by Seichis** [comment]
I ll try to see if the tutorial on mobile services works

**Comment by adrianhall** [comment]
The JavaScript Client SDK has not been released yet - only a Cordova plugin.  Once the JS Client is released, we will work on docs.  In the mean time, the Cordova plugin is documented here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-cordova-how-to-use-client-library/ - the HTML library uses much of the same code.
