### ISSUE TITLE
Create typings (.d.ts)

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-mobile-apps-js-client#79]
Would be nice to include .d.ts along with the js files to ensure we have intellisense.

**Comment by PaulARoy** [comment]
God yes, it would be awesome.

**Comment by Ross-Rawlins** [comment]
+1

**Comment by elamalani** [comment]
@rido-min Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). At this point, we are not adding new features to this product.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
