### ISSUE TITLE
SPIKE: Figure out how to deal with auth on local development

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#8]
There is a requirement to deal with authentication in local development (ref: alter the redirect URL to support this scenario)

**Comment by shrishrirang** [comment]
@adrianhall : Can this be closed now that `alternateLoginHost` and `loginUriPrefix` are implemented?

**Comment by adrianhall** [comment]
Yes - can be closed, providing we have verified we can run a local server/local client with auth provided by an app service.
