### ISSUE TITLE
Browser pop-up login does not complete

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#81]
Set up a pop-up login within a browser

```
// Create the client and endpoint, then export them so others can use them easily.
let azureClient = new WindowsAzure.MobileServiceClient(azureEndpoint); // eslint-disable-line new-cap
console.info('azureClient = ', azureClient);
azureClient.login('google').then(success, failure);
```

Login process goes through a pop-up window.  After the pop-up completes, /.auth/login/google/callback is called.  Window does not close.  Closing window calls the failure function with a 'canceled' error message.

**Comment by adrianhall** [comment]
For code to implement, see https://github.com/adrianhall/react-todo-qs (branch: azure)

To build:
```
npm install
npm run nodemon
```

Browser can hit http://localhost:3000 (endpoint has CORS disabled)

**Comment by shrishrirang** [comment]
Is this even after setting the allowedExternalRedirectUrls and allowedOrigins (CORS) properties? Is it only for 'google' or all providers? I just checked and it worked for all providers.

**Comment by shrishrirang** [comment]
You need to add your site URL to the allowedExternalRedirectUrls list. To do this:

- Open your Mobile App in portal.azure.com
- Go to Tools -> Resource explorer
- In your site's settings in the left pane of the resource explorer, open config -> authsettings and add http://<your site name> and https://<your site name> to the allowedExternalRedirectUrls array. This will fix the auth server flow.
- In your site's settings in the left pane of the resource explorer, open config -> web and add http://<your site name> and https://<your site name> to the allowedOrigins array. You can also do this using the CORS UI in your site's settings in the portal. This will fix the auth client flow.
- Wait for a few seconds for the settings to take effect and then run your scenario.

**Comment by limcheepei** [comment]
Hi,
I am also having this problem. If my site is https://mride.azurewebsites.net, and I am running Ionic framework (using Cordova), do I add https://mride.azurewebsites.net and https://mride.azurewebsites.net  to both allowedExternalRedirectUrls and CORS ?
