### ISSUE TITLE
Bug: ionic - Windows Azure is not defined 

### ISSUE THREAD

**Issue by huskywhale** [Azure/azure-mobile-apps-js-client#85]
ReferenceError: WindowsAzure is not defined 

> var client = new WindowsAzure.MobileServiceClient("SITE","KEY");

I am using ionic 1.5. 

Installed the plugin using

> sh-3.2# ionic plugin add  cordova-plugin-ms-azure-mobile-apps

Any help ?

**Comment by shrishrirang** [comment]
Do you see the plugin in your platform directory? Can you check if it is being loaded? I am assuming your code runs after the 'deviceready' event is fired.

Also, this plugin is intended for use with Mobile Apps and you don't need to specify a key in the constructor anymore. Refer the example at https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps.

**Comment by huskywhale** [comment]
Yes, it is being loaded in the plugin and its loaded after the page is loaded.

I am using it in my login function 
<img width="1280" alt="screen shot 2016-03-11 at 12 56 29 pm" src="https://cloud.githubusercontent.com/assets/9066230/13710661/a19b0fb6-e788-11e5-9c2a-3e2b17b905ec.png">

**Comment by huskywhale** [comment]
It was being trigged by not being ondeviceready.

**Comment by adrianhall** [comment]
Thanks - I'll update the HOWTO documentation to make this clear.
