### ISSUE TITLE
Backward Compatiblity with application key

### ISSUE THREAD

**Issue by huskywhale** [Azure/azure-mobile-apps-js-client#86]
The Version 1.8 Supports application key 
```
function MobileServiceClient(applicationUrl, applicationKey) {
		    /// <summary>
		    /// Initializes a new instance of the MobileServiceClient class.
		    /// </summary>
		    /// <param name="applicationUrl" type="string" mayBeNull="false">
		    /// The URL to the Mobile Services application.
		    /// </param>
		    /// <param name="applicationKey" type="string" mayBeNull="false">
		    /// The Mobile Service application's key.
		    /// </param>
```
Meanwhile the current beta doesn't. The previous version fails on PhoneGap build on ios and Android M. 

Is there any guide where i can make changes to backend in this regard.

**Comment by shrishrirang** [comment]
What backend are you currently using? Is it Mobile Services or Mobile Apps?

**Comment by huskywhale** [comment]
Mobile services.

**Comment by huskywhale** [comment]
https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-migrating-from-mobile-services/

**Comment by shrishrirang** [comment]
In addition, https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-node-backend-upgrading-from-mobile-services/ talks about upgrading to Mobile Apps. https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-node-backend-how-to-use-server-sdk/ talks about the Mobile Apps nodejs sdk in detail.

**Comment by huskywhale** [comment]
Thanks for the quick response. I will just try to experiment with methods from 1.8 and B4. Migrate tom if it doesnt work.

will close the issue tomorrow, if i fail.

**Comment by shrishrirang** [comment]
There are few other differences like authentication in the Cordova clients for Mobile Services and Mobile Apps. The Mobile Apps client (beta4) isn't intended to be compatible with the Mobile Services backend. In the short term you can try your approach.

For my information what is the error you are running into on Android and iOS? Also, can you link me to the plugin you are using?

**Comment by huskywhale** [comment]
Plugin for mobile services
https://github.com/Azure/azure-mobile-services-cordova

There is an error during run time in the following code
 ```
 Promise.prototype.done = function (success, error) {
		        this.then(success, error).then(null, function(err) {
		            // "done" throws any final errors as global uncaught exceptions. The setTimeout
		            // ensures the exception won't get caught in the Promises machinery or user code.
		            setTimeout(function () { throw new Error(err); }, 1);
		        });
		        return undefined; // You can't chain onto a .done()
		    };
```
I thought the mobile services were closed inorder to be replaced mobile apps. 

 Correct me if i am wrong

**Comment by shrishrirang** [comment]
Thanks! It will be good if you can share the repro steps so that I can take a look too.

Your understanding of Mobile Apps is correct. I was referring to subtle changes in the Mobile Apps backend like REST endpoints for authentication which makes the Mobile Apps client incompatible with the Mobile Services backend.

**Comment by shrishrirang** [comment]
No response for a long time, closing the issue.
