### ISSUE TITLE
Deprecate WinJS Support

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#87]
We will no longer be supporting WinJS.  Please close all issues related to WinJS, remove E2E tests and build artifacts.

**Comment by adrianhall** [comment]
Issue Refs: #42 (probably delete), #11, #13 (adjust to not cover WinJS case)

**Comment by shrishrirang** [comment]
Just as a note - #11 is applicable to auth in Win* platforms, unless we are saying we don't want the Windows-ish auth experience (example: Single Sign On) on Cordova Windows. The primary difference between Cordova Windows and Cordova for other platforms is that we use Windows Authentication Broker on Windows and a regular browser window on others.

**Comment by adrianhall** [comment]
Agreed on your coverage - just wanted to note that WinJS testing is not a requirement.
