### ISSUE TITLE
Test Cordova server-directed login flow

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#9]
Cordova (native env.)

Investigate and test the server-directed login flow in Cordova.  Test impact of cookies returned from EasyAuth.

**Comment by shrishrirang** [comment]
Commit f8469065199e6314e4c85c8f1699ee87ea32cd2b closes #9.
- Server directed flow works now.
- EA has a check which forbids access to public tables if the request has an auth token but not auth cookie. This forbids access to public table after a successful signin followed by a logout. To fix this, login requests to EA will now add a query string 'session_mode=token' to request only the auth token from EA (Cookie will not be returned by EA any more).
