### ISSUE TITLE
Support Auth token refresh logic

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-js-client#92]
Per http://cgillum.tech/2016/03/07/app-service-token-store/

We need to support client.refresh() that will refresh the auth tokens.  A basic implementation that calls the refresh with X-ZUMO-AUTH and sets the mobile service auth token before resolving/rejecting the token would be enough to start.

**Comment by tanviraumi** [comment]
Is this feature available now?

**Comment by elamalani** [comment]
@tanviraumi Thanks for using Azure Mobile Apps. Please read the Readme section on this repo which talks about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-js-client#future-of-azure-mobile-apps). At this point, we are not adding new features to this product.

I'll close this issue for now, but feel free to ask us questions if you have any. Thanks!
